"""Definición COMPACTA de COBOL — de Grace Hopper (1959) al estándar 2023.

Organizada POR ERA/ESTÁNDAR: cada palabra sabe cuándo entró. Python expande
esto a tablas Rust verbosas. Crecer estas listas = crecer el parser Rust
SOLO. Python es la fábrica; NUNCA entra a BMO (solo se commitea el Rust).

Fuentes (conocimiento público de los estándares; ampliar hacia el texto
completo ISO 1989:2023): COBOL-60/68/74 (Hopper/CODASYL), ANSI-85,
ISO 2002 (OO), ISO 2014, ISO 2023.
"""

# ── Palabras reservadas por estándar que las introdujo/consolidó ──────────
# El valor es el "primer estándar" canónico donde la palabra es reservada.
RESERVED_BY_STANDARD = {
    # COBOL-60/74: el núcleo de Grace Hopper y CODASYL.
    "COBOL74": [
        "IDENTIFICATION", "ENVIRONMENT", "DATA", "PROCEDURE", "DIVISION",
        "SECTION", "PROGRAM-ID", "AUTHOR", "WORKING-STORAGE", "FILE",
        "LINKAGE", "CONFIGURATION", "INPUT-OUTPUT", "FILE-CONTROL",
        "ACCEPT", "ADD", "ALTER", "CALL", "CLOSE", "DISPLAY", "DIVIDE",
        "EXIT", "GO", "IF", "MOVE", "MULTIPLY", "OPEN", "PERFORM", "READ",
        "WRITE", "REWRITE", "STOP", "SUBTRACT", "SORT", "MERGE", "SET",
        "PIC", "PICTURE", "VALUE", "OCCURS", "REDEFINES", "USAGE", "COMP",
        "COMPUTATIONAL", "DISPLAY", "BINARY", "SIGN", "LEADING", "TRAILING",
        "SEPARATE", "FILLER", "BLANK", "JUSTIFIED", "SYNCHRONIZED",
        "ELSE", "THEN", "UNTIL", "VARYING", "THROUGH", "THRU", "TIMES",
        "GIVING", "REMAINDER", "ROUNDED", "ON", "SIZE", "ERROR",
        "OVERFLOW", "NOT", "AND", "OR", "TO", "FROM", "BY", "INTO",
        "EQUAL", "GREATER", "LESS", "THAN", "ZERO", "ZEROS", "ZEROES",
        "SPACE", "SPACES", "HIGH-VALUE", "HIGH-VALUES", "LOW-VALUE",
        "LOW-VALUES", "QUOTE", "QUOTES", "ALL", "OF", "IN", "IS", "ARE",
        "USING", "RUN", "STANDARD", "LABEL", "RECORD", "RECORDS", "BLOCK",
        "SELECT", "ASSIGN", "ORGANIZATION", "ACCESS", "SEQUENTIAL",
        "INDEXED", "RELATIVE", "KEY", "STATUS", "AT", "END", "INVALID",
        "DEPENDING", "ASCENDING", "DESCENDING", "COUNT", "TALLYING",
        "REPLACING", "INSPECT", "STRING", "UNSTRING", "DELIMITED",
        "DELIMITER", "POINTER", "ADVANCING", "PAGE", "LINE", "LINES",
    ],
    # ANSI-85: estructura moderna (scope terminators, EVALUATE, INITIALIZE).
    "COBOL85": [
        "EVALUATE", "WHEN", "CONTINUE", "INITIALIZE", "CANCEL", "GOBACK",
        "END-IF", "END-PERFORM", "END-EVALUATE", "END-READ", "END-WRITE",
        "END-ADD", "END-SUBTRACT", "END-MULTIPLY", "END-DIVIDE",
        "END-COMPUTE", "END-CALL", "END-STRING", "END-UNSTRING",
        "END-SEARCH", "END-START", "END-DELETE", "END-REWRITE",
        "END-RETURN", "END-ACCEPT", "END-DISPLAY", "COMPUTE", "SEARCH",
        "RELEASE", "RETURN", "START", "DELETE", "REFERENCE", "CONTENT",
        "GLOBAL", "EXTERNAL", "COMMON", "TRUE", "FALSE", "ANY", "OTHER",
        "PACKED-DECIMAL",
    ],
    # ISO-2002: orientación a objetos + intrínsecas.
    "COBOL2002": [
        "CLASS", "CLASS-ID", "OBJECT", "METHOD", "METHOD-ID", "FACTORY",
        "INHERITS", "INVOKE", "SELF", "SUPER", "OVERRIDE", "FUNCTION",
        "RAISING", "EXCEPTION", "RESUME", "LOCAL-STORAGE", "TYPEDEF",
        "PROPERTY", "GET", "REPOSITORY", "INTERFACE", "INTERFACE-ID",
        "BASED", "BIT", "BOOLEAN", "VAL-STATUS", "VALIDATE", "FORMAT",
    ],
    # ISO-2014 / 2023: refinamientos modernos.
    "COBOL2023": [
        "ALLOCATE", "FREE", "JSON", "XML", "GENERATE", "PARSE",
        "ACTIVE-CLASS", "ALIGNED", "AWAY-FROM-ZERO", "NEAREST-EVEN",
        "PROHIBITED", "TRUNCATION", "STANDARD-BINARY", "STANDARD-DECIMAL",
        "FLOAT-SHORT", "FLOAT-LONG", "FLOAT-EXTENDED", "USER-DEFAULT",
    ],
}

# ── Lista COMPREHENSIVA (unión de estándares + extensiones comunes) ───────
# Fuente autoritativa: Gordon College CS323 COBOL reserved words
# (https://cs.gordon.edu/courses/cs323/COBOL/COBOL-reservedWords.html), unión
# de ANSI/ISO + extensiones IBM/VAX. GnuCOBOL define 1130+ según dialecto
# (cobc --list-reserved); esto es un núcleo amplio y real. Las que ya están
# etiquetadas por era arriba conservan su era; el resto queda como "COMMON".
RESERVED_COMMON = [
    "ACCEPT", "ACCESS", "ADD", "ADDRESS", "ADVANCING", "AFTER", "ALL",
    "ALLOWING", "ALPHABET", "ALPHABETIC", "ALPHABETIC-LOWER",
    "ALPHABETIC-UPPER", "ALPHANUMERIC", "ALPHANUMERIC-EDITED", "ALSO",
    "ALTER", "ALTERNATE", "AND", "ANY", "APPLY", "ARE", "AREA", "AREAS",
    "ASCENDING", "ASSIGN", "AT", "AUTHOR", "AUTO", "AUTOMATIC",
    "AUTOTERMINATE", "BACKGROUND-COLOR", "BATCH", "BEFORE", "BEGINNING",
    "BELL", "BINARY", "BINARY-CHAR", "BINARY-DOUBLE", "BINARY-LONG",
    "BINARY-SHORT", "BIT", "BITS", "BLANK", "BLINK", "BLINKING", "BLOCK",
    "BOLD", "BOOLEAN", "BOTTOM", "BY", "CALL", "CANCEL", "CD", "CF", "CH",
    "CHANGED", "CHARACTER", "CHARACTERS", "CLASS", "CLOCK-UNITS", "CLOSE",
    "COBOL", "CODE", "CODE-SET", "COL", "COLLATING", "COLUMN", "COMMA",
    "COMMIT", "COMMON", "COMMUNICATION", "COMP", "COMP-1", "COMP-2",
    "COMP-3", "COMP-4", "COMP-5", "COMP-6", "COMP-X", "COMPUTATIONAL",
    "COMPUTATIONAL-1", "COMPUTATIONAL-2", "COMPUTATIONAL-3",
    "COMPUTATIONAL-4", "COMPUTATIONAL-5", "COMPUTATIONAL-6",
    "COMPUTATIONAL-X", "COMPUTE", "CONCURRENT", "CONFIGURATION", "CONNECT",
    "CONTAIN", "CONTAINS", "CONTENT", "CONTINUE", "CONTROL", "CONTROLS",
    "CONVERSION", "CONVERTING", "COPY", "CORE-INDEX", "CORR",
    "CORRESPONDING", "COUNT", "CRT", "CURRENCY", "CURRENT", "CURSOR",
    "DATA", "DATE", "DATE-COMPILED", "DATE-WRITTEN", "DAY", "DAY-OF-WEEK",
    "DB", "DBCS", "DBKEY", "DE", "DEBUGGING", "DECIMAL-POINT",
    "DECLARATIVES", "DEFAULT", "DELETE", "DELIMITED", "DELIMITER",
    "DEPENDENCY", "DEPENDING", "DESCENDING", "DESCRIPTOR", "DESTINATION",
    "DETAIL", "DICTIONARY", "DISABLE", "DISCONNECT", "DISP", "DISPLAY",
    "DISPLAY-1", "DIVIDE", "DIVISION", "DOES", "DOWN", "DUPLICATE",
    "DUPLICATES", "ECHO", "EDITING", "EGI", "EJECT", "ELSE", "EMI",
    "EMPTY", "ENABLE", "END", "END-ACCEPT", "END-ADD", "END-CALL",
    "END-COMPUTE", "END-DELETE", "END-DIVIDE", "END-EVALUATE",
    "END-IF", "END-MULTIPLY", "END-OF-PAGE", "END-PERFORM", "END-READ",
    "END-RECEIVE", "END-RETURN", "END-REWRITE", "END-SEARCH", "END-START",
    "END-STRING", "END-SUBTRACT", "END-UNSTRING", "END-WRITE", "ENDING",
    "ENTER", "ENTRY", "ENVIRONMENT", "EOL", "EOP", "EOS", "EQUAL",
    "EQUALS", "ERASE", "ERROR", "ESI", "EVALUATE", "EVERY", "EXAMINE",
    "EXCEEDS", "EXCEPTION", "EXCLUSIVE", "EXHIBIT", "EXIT", "EXOR",
    "EXTEND", "EXTERNAL", "FAILURE", "FALSE", "FD", "FETCH", "FILE",
    "FILE-CONTROL", "FILLER", "FINAL", "FIND", "FINISH", "FIRST",
    "FLOAT-EXTENDED", "FLOAT-LONG", "FLOAT-SHORT", "FOOTING", "FOR",
    "FOREGROUND-COLOR", "FREE", "FROM", "FULL", "FUNCTION", "GENERATE",
    "GET", "GIVING", "GLOBAL", "GO", "GOBACK", "GREATER", "GROUP",
    "HEADING", "HIGH-VALUE", "HIGH-VALUES", "HIGHLIGHT", "I-O",
    "I-O-CONTROL", "ID", "IDENT", "IDENTIFICATION", "IF", "IN",
    "INCLUDING", "INDEX", "INDEXED", "INDICATE", "INITIAL", "INITIALIZE",
    "INITIATE", "INPUT", "INPUT-OUTPUT", "INSPECT", "INSTALLATION",
    "INTO", "INVALID", "IS", "JUST", "JUSTIFIED", "KANJI", "KEEP", "KEY",
    "LABEL", "LAST", "LD", "LEADING", "LEFT", "LENGTH", "LESS", "LIMIT",
    "LIMITS", "LINAGE", "LINAGE-COUNTER", "LINE", "LINE-COUNTER", "LINES",
    "LINKAGE", "LOCALLY", "LOCK", "LOCK-HOLDING", "LOW-VALUE",
    "LOW-VALUES", "LOWLIGHT", "MANUAL", "MATCH", "MATCHES", "MEMBER",
    "MEMBERSHIP", "MEMORY", "MERGE", "MESSAGE", "MODE", "MODIFY",
    "MODULES", "MOVE", "MULTIPLE", "MULTIPLY", "NAMED", "NATIVE",
    "NEGATIVE", "NEXT", "NO", "NON-NULL", "NOT", "NOTE", "NULL", "NUMBER",
    "NUMERIC", "NUMERIC-EDITED", "OBJECT-COMPUTER", "OCCURS", "OF", "OFF",
    "OFFSET", "OMITTED", "ON", "ONLY", "OPEN", "OPTIONAL", "OPTIONS",
    "OR", "ORDER", "OTHERWISE", "PACKED-DECIMAL", "PADDING", "PAGE",
    "PAGE-COUNTER", "PASSWORD", "PERFORM", "PF", "PH", "PIC", "PICTURE",
    "PLUS", "POINTER", "POSITION", "POSITIONING", "POSITIVE", "PREVIOUS",
    "PRINTING", "PRIOR", "PROCEDURE", "PROCEDURES", "PROCEED", "PROGRAM",
    "PROGRAM-ID", "PROTECTED", "PURGE", "QUEUE", "QUOTE", "QUOTES",
    "RANDOM", "RD", "READ", "READERS", "READY", "REALM", "REALMS",
    "RECEIVE", "RECONNECT", "RECORD", "RECORD-NAME", "RECORD-OVERFLOW",
    "RECORDING", "RECORDS", "REDEFINES", "REEL", "REFERENCE",
    "REFERENCE-MODIFIER", "REFERENCES", "REGARDLESS", "RELATIVE",
    "RELEASE", "RELOAD", "REMAINDER", "REMARKS", "REMOVAL", "RENAMES",
    "REPLACE", "REPLACING", "REPORT", "REPORTING", "REPORTS", "REQUIRED",
    "RERUN", "RESERVE", "RESET", "RETAINING", "RETRIEVAL", "RETURN",
    "RETURN-CODE", "RETURNING", "REVERSE-VIDEO", "REVERSED", "REWIND",
    "REWRITE", "RF", "RH", "RIGHT", "ROLLBACK", "ROUNDED", "RUN", "SAME",
    "SCREEN", "SD", "SEARCH", "SECTION", "SECURE", "SECURITY", "SEGMENT",
    "SEGMENT-LIMIT", "SELECT", "SEND", "SENTENCE", "SEPARATE", "SEQUENCE",
    "SEQUENCE-NUMBER", "SEQUENTIAL", "SERVICE", "SET", "SETS", "SIGN",
    "SIGNED", "SIZE", "SKIP1", "SKIP2", "SKIP3", "SORT", "SORT-MERGE",
    "SOURCE", "SOURCE-COMPUTER", "SPACE", "SPACES", "SPECIAL-NAMES",
    "STANDARD", "STANDARD-1", "STANDARD-2", "START", "STATUS", "STOP",
    "STORE", "STREAM", "STRING", "SUB-QUEUE-1", "SUB-QUEUE-2",
    "SUB-QUEUE-3", "SUB-SCHEMA", "SUBTRACT", "SUCCESS", "SUM", "SUPPRESS",
    "SYMBOLIC", "SYNC", "SYNCHRONIZED", "TABLE", "TALLYING", "TAPE",
    "TENANT", "TERMINAL", "TERMINATE", "TEST", "TEXT", "THAN", "THEN",
    "THROUGH", "THRU", "TIME", "TIMES", "TO", "TOP", "TRACE", "TRAILING",
    "TRANSFORM", "TRUE", "TYPE", "UNDERLINE", "UNDERLINED", "UNEQUAL",
    "UNIT", "UNLOCK", "UNSIGNED", "UNSTRING", "UNTIL", "UP", "UPDATE",
    "UPDATERS", "UPON", "USAGE", "USAGE-MODE", "USE", "USING", "VALUE",
    "VALUES", "VARYING", "VFU-CHANNEL", "WAIT", "WHEN", "WHERE", "WITH",
    "WITHIN", "WORDS", "WORKING-STORAGE", "WRITE", "WRITERS", "ZERO",
    "ZEROES", "ZEROS",
]

# ── Verbos con codegen (palabra COBOL -> variante CobolStatement) ─────────
VERBS = {
    "DISPLAY": "Display",
    "ACCEPT": "Accept",
    "MOVE": "Move",
    "ADD": "Add",
    "SUBTRACT": "Subtract",
    "MULTIPLY": "Multiply",
    "DIVIDE": "Divide",
    "COMPUTE": "Compute",
    "IF": "If",
    "PERFORM": "Perform",
    "OPEN": "Open",
    "CLOSE": "Close",
    "READ": "Read",
    "WRITE": "Write",
    "STOP": "StopRun",
}

# ── Funciones intrínsecas (ISO-2002+) — se generan a su propia tabla ──────
INTRINSIC_FUNCTIONS = [
    "ABS", "ACOS", "ANNUITY", "ASIN", "ATAN", "BYTE-LENGTH", "CHAR",
    "COS", "CURRENT-DATE", "DATE-OF-INTEGER", "DAY-OF-INTEGER", "E",
    "EXP", "FACTORIAL", "INTEGER", "INTEGER-OF-DATE", "INTEGER-PART",
    "LENGTH", "LOG", "LOG10", "LOWER-CASE", "MAX", "MEAN", "MEDIAN",
    "MIDRANGE", "MIN", "MOD", "NUMVAL", "NUMVAL-C", "ORD", "ORD-MAX",
    "ORD-MIN", "PI", "PRESENT-VALUE", "RANDOM", "RANGE", "REM",
    "REVERSE", "SIN", "SQRT", "STANDARD-DEVIATION", "SUM", "TAN",
    "TRIM", "UPPER-CASE", "VARIANCE", "WHEN-COMPILED",
    # 2023
    "FORMATTED-CURRENT-DATE", "FORMATTED-DATE", "FORMATTED-TIME",
    "CONCATENATE", "SUBSTITUTE", "BIT-OF", "BIT-TO-CHAR", "HEX-OF",
]
