[workspace]
resolver = "2"
members = [
    "kernel",
    "crates_Personal/bootloader",
    "crates_Personal/boot_protocol",
    "crates_Personal/bmo_abi",
    "crates_Personal/bmo_audio",
    "crates_Personal/nvram-log",
    "crates_Personal/vendor",
    "crates_Personal/cabina/core",
    "crates_Personal/cabina/daemon",
    "crates_Personal/cabina/panels",
    "crates_Personal/bmo_core",
    "crates_Personal/hw_profile",
    "crates_Personal/bmo_input",
    "crates_Personal/bmo_ahci",
    "crates_Personal/bmo_fat32",
    "crates_Personal/bmo_xhci",
    "crates_Personal/bmo_uhid",
    "crates_Personal/cpu_vendor_profile",
    "crates_Personal/byte_defender",
    "crates_Personal/timeback",
    "crates_Personal/Lenguajes/cobol",
    "crates_Personal/Lenguajes/cpp",
    "crates_Personal/Lenguajes/c",
    "crates_Personal/userland_ring3",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1
strip = "symbols"
debug = false
debug-assertions = false
overflow-checks = false
