[workspace]
resolver = "2"
members = [
    "kernel",
    "crates_Personal/bootloader",
    "crates_Personal/ring0/boot_protocol",
    "crates_Personal/abi/bmo_abi",
    "crates_Personal/drivers/audio/audio",
    "crates_Personal/shared/nvram_log",
    "crates_Personal/vendor",
    "crates_Personal/services/cabina/core",
    "crates_Personal/services/cabina/daemon",
    "crates_Personal/services/cabina/panels",
    "crates_Personal/desktop/bmo_core",
    "crates_Personal/shared/hw_profile",
    "crates_Personal/drivers/usb/input",
    "crates_Personal/drivers/storage/ahci",
    "crates_Personal/drivers/storage/fat32",
    "crates_Personal/drivers/usb/xhci",
    "crates_Personal/drivers/usb/uhid",
    "crates_Personal/ring0/cpu_vendor_profile",
    "crates_Personal/services/byte_defender",
    "crates_Personal/services/timeback",
    "crates_Personal/tools/languages/cobol",
    "crates_Personal/tools/languages/cpp",
    "crates_Personal/tools/languages/c",
    "crates_Personal/shared/hal_defs",
    "crates_Personal/modules/bmo_core",
    "crates_Personal/modules/timeback",
    "crates_Personal/modules/cabina",
    "crates_Personal/drivers/storage/nvme",
    "crates_Personal/drivers/net/net",
    "crates_Personal/abi/userland_ring3",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 3
lto = true
codegen-units = 1
strip = "symbols"
debug = false
debug-assertions = false
overflow-checks = false
