//! Shell commands — command dispatch for the welcome screen.

#![allow(dead_code)]

/// Case-insensitive comparison.
pub fn eq_ci(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    for i in 0..a.len() {
        let ca = a[i].to_ascii_lowercase();
        let cb = b[i].to_ascii_lowercase();
        if ca != cb { return false; }
    }
    true
}

/// Check if command should enter the desktop.
pub fn should_enter_desktop(cmd: &[u8]) -> bool {
    eq_ci(cmd, b"run") || eq_ci(cmd, b"desktop") || eq_ci(cmd, b"start") || eq_ci(cmd, b"go")
}

/// Trim whitespace from both ends of a byte slice.
pub fn trim(s: &[u8]) -> &[u8] {
    let mut i = 0;
    while i < s.len() && s[i] == b' ' { i += 1; }
    let mut j = s.len();
    while j > i && s[j-1] == b' ' { j -= 1; }
    &s[i..j]
}

/// Enter the desktop environment.
///
/// v1.7.2: el stub "DESKTOP STUB v1.6.21" se reemplaza por el
/// BMO API v2.0 desktop real (`bmo_api::wm::enter`). Ese módulo
/// crea ventanas top-level (Terminal, Datos.md viewer, Ajustes),
/// inicia el window manager con Z-order, focus-follows-mouse, drag,
/// resize, snap y modal, y entra en el loop principal. ESC devuelve
/// al welcome.
pub fn enter_desktop() {
    crate::bmo_core::diag::set_overlay_enabled(false);
    crate::bmo_core::diag::info("welcome", "Run accepted; entering BMO API v2 desktop");
    crate::dev::console::serial_write(
        "[welcome] Run aceptado: BMO API v2.0 desktop real.\n",
    );
    crate::bmo_core::bmo_api::wm::enter()
}

/// Test compile a ÑEXO program.
pub fn nexo_test_compile() {
    use crate::bmo_core::lang::bmo;
    let source = b"fn main() -> num { retorna 42 }\n";
    crate::bmo_core::diag::info("nexo", "Compiling test program");
    match bmo::compile(source) {
        Ok(bytes) => {
            crate::bmo_core::diag::info("nexo", "Compilation succeeded");
            crate::bmo_core::diag::info_u64("nexo", "Generated bytes", bytes.len() as u64);
            crate::bmo_core::diag::info_u64("nexo", "First byte", bytes.first().copied().unwrap_or(0) as u64);
        }
        Err(_e) => {
            crate::bmo_core::diag::warn("nexo", "Compilation failed");
        }
    }
}
