[package]
name = "mod-bmo-core"
version = "1.0.0"
edition = "2021"
authors = ["BMO Project"]
description = "BMO Core module — loaded by kernel.elf as a separate binary"

[dependencies]
bmo-core = { path = "../../desktop/bmo_core" }
bmo-hal = { path = "../../../Uso_Reales_Crates/shared/bmo-hal" }
timeback = { path = "../../../Uso_Reales_Crates/services/timeback" }
byte-defender = { path = "../../../Uso_Reales_Crates/services/byte-defender" }
goblin = { path = "../../plugins/goblin", default-features = false, features = ["alloc", "elf32", "elf64", "endian_fd"] }
"bmo-xhci" = { path = "../../drivers/usb/xhci" }
"bmo-uhid" = { path = "../../drivers/usb/uhid" }
"bmo-input" = { path = "../../drivers/usb/input" }
ring3-foundation = { path = "../../../kernel/ring3/foundation" }
