//! Shell commands — command dispatch for the welcome screen.

#![allow(dead_code)]

/// Case-insensitive comparison.
pub fn eq_ci(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    for i in 0..a.len() {
        let ca = a[i].to_ascii_lowercase();
        let cb = b[i].to_ascii_lowercase();
        if ca != cb { return false; }
    }
    true
}

/// Check if command should enter the desktop.
pub fn should_enter_desktop(cmd: &[u8]) -> bool {
    eq_ci(cmd, b"run") || eq_ci(cmd, b"desktop") || eq_ci(cmd, b"start") || eq_ci(cmd, b"go")
}

/// Trim whitespace from both ends of a byte slice.
pub fn trim(s: &[u8]) -> &[u8] {
    let mut i = 0;
    while i < s.len() && s[i] == b' ' { i += 1; }
    let mut j = s.len();
    while j > i && s[j-1] == b' ' { j -= 1; }
    &s[i..j]
}

/// Enter the desktop environment (calls into sched::user_init).
///
/// v1.5.3: DESKTOP STUBBED — instead of running the desktop loop
/// (which can hang in paint_overlay or poll_key), we just show a
/// red bar "DESKTOP STUBBED" and return to welcome.
pub fn enter_desktop() {
    crate::diag::set_overlay_enabled(false);
    crate::diag::info("welcome", "Run accepted; desktop STUBBED in v1.5.3 (use ESC/welcome to recover)");
    crate::drivers::serial::serial_write("[welcome] Run aceptado: DESKTOP STUBBED en v1.5.3.\n");

    // Show a big red bar to indicate "stubbed mode"
    let fb = crate::drivers::gop::get_backbuffer_fb();
    {
        let w = 1920u32;
        let h = 1080u32;
        // Big red rectangle in the middle
        crate::desktop::display::fb_fill(50, h / 4, w - 100, 80, 0x00FF2A2A);
        // Text overlay
        crate::desktop::display::fb_text(
            100,
            (h / 4 + 20),
            b"[DESKTOP STUBBED] v1.5.3: ring0 desktop loop is disabled. Return to welcome.",
            0xFFFFFFFF,
        );
        let _ = fb; // silence unused
    }

    // Simulate a 500ms delay so user sees the message
    crate::arch::cpu::busy_wait_ms(500);

    // Return to welcome (no re-paint needed; welcome::run re-paints)
}

/// Test compile a ÑEXO program.
pub fn nexo_test_compile() {
    use crate::lang::nexo;
    let source = b"fn main() -> num { retorna 42 }\n";
    crate::diag::info("nexo", "Compiling test program");
    match nexo::compile(source) {
        Ok(bytes) => {
            crate::diag::info("nexo", "Compilation succeeded");
            crate::diag::info_u64("nexo", "Generated bytes", bytes.len() as u64);
            crate::diag::info_u64("nexo", "First byte", bytes.first().copied().unwrap_or(0) as u64);
        }
        Err(_e) => {
            crate::diag::warn("nexo", "Compilation failed");
        }
    }
}
