//! Shell commands — command dispatch for the welcome screen.

#![allow(dead_code)]

/// Case-insensitive comparison.
pub fn eq_ci(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    for i in 0..a.len() {
        let ca = a[i].to_ascii_lowercase();
        let cb = b[i].to_ascii_lowercase();
        if ca != cb { return false; }
    }
    true
}

/// Check if command should enter the desktop.
pub fn should_enter_desktop(cmd: &[u8]) -> bool {
    eq_ci(cmd, b"run") || eq_ci(cmd, b"desktop") || eq_ci(cmd, b"start") || eq_ci(cmd, b"go")
}

/// Trim whitespace from both ends of a byte slice.
pub fn trim(s: &[u8]) -> &[u8] {
    let mut i = 0;
    while i < s.len() && s[i] == b' ' { i += 1; }
    let mut j = s.len();
    while j > i && s[j-1] == b' ' { j -= 1; }
    &s[i..j]
}

/// Enter the desktop environment (calls into sched::user_init).
///
/// v1.5.4: DESKTOP STUBBED — shows red bar then EXITS the welcome loop
/// with a clear message. The user can power-cycle to re-enter.
/// (v1.5.3 had a bug: re-entered welcome::run which re-painted on top
/// of the red bar, looking like a hang.)
pub fn enter_desktop() {
    crate::diag::set_overlay_enabled(false);
    crate::diag::info("welcome", "Run accepted; desktop STUBBED in v1.5.4 (REBOOT to return to welcome)");
    crate::drivers::serial::serial_write("[welcome] Run aceptado: DESKTOP STUBBED en v1.5.4. Reboot to recover.\n");

    // Show a big red bar with clear instructions
    let fb = crate::drivers::gop::get_backbuffer_fb();
    {
        let w = 1920u32;
        let h = 1080u32;
        // Clear screen first
        crate::desktop::display::fb_fill(0, 0, w, h, 0x00000000);
        // Big red rectangle in the middle
        crate::desktop::display::fb_fill(50, h / 4, w - 100, 100, 0x00FF2A2A);
        // Text overlay
        crate::desktop::display::fb_text(
            100,
            (h / 4 + 20),
            b"[DESKTOP STUBBED] v1.5.4",
            0xFFFFFFFF,
        );
        crate::desktop::display::fb_text(
            100,
            (h / 4 + 50),
            b"The ring0 desktop loop is disabled in v1.5.x for stability.",
            0xFFFFFFFF,
        );
        crate::desktop::display::fb_text(
            100,
            (h / 4 + 70),
            b"REBOOT the PC to return to the welcome screen.",
            0xFFFFFFFF,
        );
        let _ = fb; // silence unused
    }

    // Spin forever (with interrupts enabled) so user can reboot.
    // This is intentional: we don't trust the welcome loop re-entry.
    loop {
        unsafe { core::arch::asm!("hlt"); }
    }
}

/// Test compile a ÑEXO program.
pub fn nexo_test_compile() {
    use crate::lang::nexo;
    let source = b"fn main() -> num { retorna 42 }\n";
    crate::diag::info("nexo", "Compiling test program");
    match nexo::compile(source) {
        Ok(bytes) => {
            crate::diag::info("nexo", "Compilation succeeded");
            crate::diag::info_u64("nexo", "Generated bytes", bytes.len() as u64);
            crate::diag::info_u64("nexo", "First byte", bytes.first().copied().unwrap_or(0) as u64);
        }
        Err(_e) => {
            crate::diag::warn("nexo", "Compilation failed");
        }
    }
}
