//! Shell commands — command dispatch for the welcome screen.

#![allow(dead_code)]

/// Case-insensitive comparison.
pub fn eq_ci(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() { return false; }
    for i in 0..a.len() {
        let ca = a[i].to_ascii_lowercase();
        let cb = b[i].to_ascii_lowercase();
        if ca != cb { return false; }
    }
    true
}

/// Check if command should enter the desktop.
pub fn should_enter_desktop(cmd: &[u8]) -> bool {
    eq_ci(cmd, b"run") || eq_ci(cmd, b"desktop") || eq_ci(cmd, b"start") || eq_ci(cmd, b"go")
}

/// Trim whitespace from both ends of a byte slice.
pub fn trim(s: &[u8]) -> &[u8] {
    let mut i = 0;
    while i < s.len() && s[i] == b' ' { i += 1; }
    let mut j = s.len();
    while j > i && s[j-1] == b' ' { j -= 1; }
    &s[i..j]
}

/// Enter the desktop environment (calls into sched::user_init).
///
/// v1.6.7: DESKTOP STUBBED — shows a friendly v1.6.7 stub screen with
/// version banner, a 10-second countdown, and a hint to REBOOT to return
/// to the welcome screen. (v1.5.4 used a flat red bar that lacked version
/// context and a graceful way back.)
pub fn enter_desktop() {
    crate::diag::set_overlay_enabled(false);
    crate::diag::info("welcome", "Run accepted; desktop STUBBED in v1.6.7 (REBOOT to return to welcome)");
    crate::drivers::serial::serial_write("[welcome] Run aceptado: DESKTOP STUBBED v1.6.7. Reboot to recover.\n");

    // Render a friendly stub screen
    let w = 1920u32;
    let h = 1080u32;

    // 1) Background — dark gradient (top to bottom)
    crate::desktop::display::fb_fill(0, 0, w, h, 0xFF050B12);

    // 2) Big card in the middle (warm orange border)
    let cw = 1500u32;
    let ch = 360u32;
    let cx = (w - cw) / 2;
    let cy = (h - ch) / 2;
    crate::desktop::display::fb_fill(cx - 4, cy - 4, cw + 8, ch + 8, 0xFFE07832);
    crate::desktop::display::fb_fill(cx, cy, cw, ch, 0xFF0F1827);

    // 3) Title
    crate::desktop::display::fb_text(
        cx + 60,
        cy + 60,
        b"FastOS-BMO  ::  Desktop STUB  ::  v1.6.7",
        0xFFE2C044,
    );

    // 4) Subtitle explanation
    crate::desktop::display::fb_text(
        cx + 60,
        cy + 130,
        b"The Ring 0 desktop loop is disabled in v1.6.x for stability while we",
        0xFFCBD7E0,
    );
    crate::desktop::display::fb_text(
        cx + 60,
        cy + 150,
        b"harden the ECAM/heap path. Phase 5 (desktop) is up next in the queue.",
        0xFFCBD7E0,
    );

    // 5) Countdown — render the v1.6.7 version as a hint
    crate::desktop::display::fb_text(
        cx + 60,
        cy + 220,
        b"REBOOT the PC to return to the welcome screen.",
        0xFFFFAA3D,
    );

    // 6) Live countdown bar (10s -> 0s) — animates by HLT-loop delay
    let bar_w = cw - 120;
    let bar_x = cx + 60;
    let bar_y = cy + 280;
    let total_steps: u32 = 100;
    let total_ms: u32 = 5_000; // 5 s countdown
    let step_ms: u32 = total_ms / total_steps;
    for step in 0..total_steps {
        crate::desktop::display::fb_fill(bar_x, bar_y, bar_w, 12, 0xFF1F2A38);
        let fill_w = (bar_w as u32 * step) / total_steps;
        let color = if step < total_steps * 2 / 3 {
            0xFF4ECCA3
        } else if step < total_steps * 9 / 10 {
            0xFFE2C044
        } else {
            0xFFFF7B72
        };
        crate::desktop::display::fb_fill(bar_x, bar_y, fill_w, 12, color);
        crate::arch::cpu::busy_wait_ms(step_ms as u64);
    }

    // 7) HLT loop (rebooting is the only way back)
    loop {
        unsafe { core::arch::asm!("hlt"); }
    }
}

/// Test compile a ÑEXO program.
pub fn nexo_test_compile() {
    use crate::lang::nexo;
    let source = b"fn main() -> num { retorna 42 }\n";
    crate::diag::info("nexo", "Compiling test program");
    match nexo::compile(source) {
        Ok(bytes) => {
            crate::diag::info("nexo", "Compilation succeeded");
            crate::diag::info_u64("nexo", "Generated bytes", bytes.len() as u64);
            crate::diag::info_u64("nexo", "First byte", bytes.first().copied().unwrap_or(0) as u64);
        }
        Err(_e) => {
            crate::diag::warn("nexo", "Compilation failed");
        }
    }
}
