[workspace]

[package]
name = "mod-linux-devour"
version = "1.0.0"
edition = "2021"
description = "BMO Linux Devourer — ELF to BEF runtime converter (Ring 3 module)"

[dependencies]
bmo-hal-defs = { path = "../../shared/hal_defs" }
goblin = { path = "../../goblin", default-features = false, features = ["alloc", "elf32", "elf64", "endian_fd"] }
