[workspace]
[package]
name = "s8-syscall"
version = "2.0.0"
edition = "2021"
description = "Faggin stage 8 ? see Ultra_kernel_x86-64/faggin/README.md"

[dependencies]
serial-shared = { path = "../serial_shared" }
boot-context = { path = "../../boot_context" }


[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = 'symbols'
