//! AUTO-GENERATED BY SigDead Intelligence Exporter
//! DO NOT EDIT MANUALLY

pub struct BootStep {
    pub name: &'static str,
    pub trigger: &'static str,
    pub reg_offset: u32,
    pub reg_val: u32,
}

pub const SEC2_BRINGUP_STEPS: &[BootStep] = &[
    BootStep { name: "RESET", trigger: "PMC_ENABLE_SEC2", reg_offset: 0x000200, reg_val: 0xFFFFFFFF },
    BootStep { name: "HALTED", trigger: "BOOTVEC_SET", reg_offset: 0x840104, reg_val: 0x00000000 },
    BootStep { name: "UCODE_LOAD", trigger: "IMEM_DMEM_DMA", reg_offset: 0, reg_val: 0 },
    BootStep { name: "AUTHENTICATING", trigger: "CPUCTL_START", reg_offset: 0x840100, reg_val: 0x00000002 },
    BootStep { name: "HS_MODE", trigger: "PKC_VERIFY_SUCCESS", reg_offset: 0x840008, reg_val: 0x00000010 },
];
