//! **EL GATO** -- el logo de BMO-X, en dos mascaras de 1 bit.
//!
//! * GENERADO. No se edita a mano: sale de `docs/arte/gato_a_mascara.py`, que
//! lee `docs/arte/bmo-x-gato.jpg`. Si el logo cambia, se vuelve a correr.
//!
//! === Por que un bitmap y no una imagen ===
//!
//! El logo es **97% negro plano, 1,6% blanco y 0,9% cian**, medido. Guardarlo
//! como imagen seria pagar 24 bits por pixel para almacenar "negro" cuarenta
//! mil veces -- y una pantalla completa en BGRA son 8 MB contra el 1 MiB de
//! `MAX_BEX`. Un decodificador JPEG en `no_std` serian miles de lineas para
//! dibujar tres colores.
//!
//! Asi que el trazo va en un bit y los ojos en otro, y **el fondo no se
//! guarda** porque el fondo del splash ya es negro. Dibujar es un test de bit.
//!
//! 152x180 px - 3420 B de trazo + 3420 B de ojos =
//! **6840 bytes**. Pixeles encendidos: 1346 de trazo,
//! 276 de ojos.
//!
//! === Y por que un GATO ===
//!
//! Porque un gato se cae, se rompe algo y sigue andando. Este sistema se niega
//! a arrancar un programa antes que escribir en su memoria una direccion que no
//! ha podido calcular, y cuando el escritorio muere guarda sus ultimas cuatro
//! lineas para poder decir DONDE. No presume de no fallar: presume de contarlo.

/// THE MASKS: generated by `docs/arte/gato_a_mascara.py`. **Do not edit.**
pub(crate) mod masks;
/// El derrame de luz alrededor del trazo. Es lo que separa un neon de una
/// bombilla -- ver su cabecera.
pub(crate) mod neon;
pub(crate) use masks::*;

/// Ancho de las dos mascaras, en pixeles.
pub(crate) const ANCHO: u32 = 152;
/// Alto de las dos mascaras, en pixeles.
pub(crate) const ALTO: u32 = 180;

/// Es este pixel un OJO? Lo pregunta el dibujante, que ya sabe por `neon` que
/// esta en el nucleo y solo necesita saber de cual de los dos.
pub(crate) fn bit_ojos(i: usize) -> bool {
    OJOS[i / 8] >> (i % 8) & 1 == 1
}
