//! Ring 3 process creation from BEX images (F2).
//!
//! Pipeline: BootContext payload → `bex::inspect` (validated mapping plan)
//! → fresh user address space → frames copied/zeroed per section → user
//! stack → 16 BMO Channel estuaries mapped U/S → fabricated Ring 3 trap
//! frame → `scheduler::spawn_user`. The first timer tick after
//! `timer::enable()` preempts the shell and enters CPL3 via iretq.
//!
//! v1 deliberately keeps the section leaf frames alive for the whole life
//! of the system: the single init process does not exit-reclaim (that is
//! part of the EXIT hardening work, with per-task allocation lists).

use boot_context::BootContext;

use crate::ring0::bex;
use crate::ring0::channel;
use crate::ring0::mm::{self, phys, vmm};
use crate::ring0::scheduler;
use crate::ring0::trap;

const USER_STACK_PAGES: u64 = 16; // 64 KiB
const KERNEL_STACK_PAGES: u64 = 2; // 8 KiB trap/syscall landing

static mut TSS_PTR: u64 = 0;

/// Last outcome of `spawn_init`, kept so `phase::main` can surface it on the
/// dashboard *after* the screen is cleared (spawn_init runs before that).
static mut INIT_STATUS: &str = "not attempted";

fn set_status(s: &'static str) {
    unsafe { INIT_STATUS = s };
}

/// Human-readable result of the last `spawn_init` call, for on-screen report.
pub fn init_status() -> &'static str {
    unsafe { INIT_STATUS }
}

/// Embedded "hola mundo" Ring 3 program (generated by `toolchain/tools/hello-bex`).
/// When the boot chain reserves no Ring 3 payload, this is admitted as the
/// init process so BMO always demonstrates the full CPL3 → INVOKE → CPL0
/// chain on its own — no keyboard, no storage, no external image required.
static INIT_HELLO_BEX: &[u8] = include_bytes!("init_hello.bex");

/// Capture the TSS location from the BootContext (identity-mapped).
pub fn init(ctx: &BootContext) {
    unsafe { TSS_PTR = ctx.tss_ptr };
}

/// Update TSS.RSP0: the kernel stack the CPU switches to when Ring 3 code
/// of the *current* task takes an interrupt. Called at every switch into a
/// user task.
pub fn set_tss_rsp0(top: u64) {
    let tss = unsafe { TSS_PTR };
    if tss == 0 {
        return;
    }
    unsafe {
        ((tss + 4) as *mut u32).write_volatile(top as u32);
        ((tss + 8) as *mut u32).write_volatile((top >> 32) as u32);
    }
}

fn log(msg: &str) {
    crate::ring0::dev::console::serial_write(msg);
}

/// Load the init process from the BootContext Ring 3 payload, if one was
/// reserved by the boot chain. Returns the new TID. With no payload this
/// is a no-op so boot stays exactly as before.
pub fn spawn_init(ctx: &BootContext) -> Option<u32> {
    // Prefer a boot-chain-supplied payload; otherwise fall back to the
    // kernel-embedded hello-world so the Ring 3 chain always runs.
    let bytes: &[u8] = if ctx.ring3_payload_phys != 0 && ctx.ring3_payload_size >= 48 {
        unsafe {
            core::slice::from_raw_parts(
                mm::phys_to_virt(ctx.ring3_payload_phys) as *const u8,
                ctx.ring3_payload_size as usize,
            )
        }
    } else {
        log("[proc] no boot payload; admitting embedded init_hello.bex (Ring 3 demo)\n");
        INIT_HELLO_BEX
    };
    set_status("admitting (alloc/map)");
    let plan = match bex::inspect(bytes) {
        Ok(p) => p,
        Err(_) => {
            log("[proc] FATAL: payload failed BEX admission\n");
            set_status("BEX admission failed");
            return None;
        }
    };
    let aspace = vmm::new_address_space()?;

    // Sections: assigned sequentially from USER_IMAGE_BASE, honoring each
    // section's alignment. entry_offset is relative to the Code section.
    let mut va_cursor = vmm::USER_IMAGE_BASE;
    let mut entry_va: u64 = 0;
    for i in 0..plan.section_count {
        let s = plan.sections[i];
        let align = s.alignment as u64;
        va_cursor = (va_cursor + align - 1) & !(align - 1);
        let va_start = va_cursor;
        let pages = (s.mem_size + mm::PAGE - 1) / mm::PAGE;
        let writable = s.flags & bex::SECTION_FLAG_EXEC == 0;
        for p in 0..pages {
            let frame = phys::alloc_frame()?;
            phys::zero_frame(frame);
            let chunk = p * mm::PAGE;
            if chunk < s.file_size {
                let n = (s.file_size - chunk).min(mm::PAGE) as usize;
                unsafe {
                    core::ptr::copy_nonoverlapping(
                        bytes.as_ptr().add((s.file_offset + chunk) as usize),
                        mm::phys_to_virt(frame) as *mut u8,
                        n,
                    );
                }
            }
            if vmm::map_page(aspace, va_start + p * mm::PAGE, frame, true, writable).is_err() {
                log("[proc] FATAL: section map failed\n");
                return None;
            }
        }
        if s.kind == bex::SECTION_CODE {
            entry_va = va_start + plan.entry_offset;
        }
        va_cursor = va_start + pages * mm::PAGE;
    }
    if entry_va == 0 {
        log("[proc] FATAL: no entry point\n");
        return None;
    }

    // User stack (64 KiB) just below USER_STACK_TOP.
    for p in 0..USER_STACK_PAGES {
        let frame = phys::alloc_frame()?;
        phys::zero_frame(frame);
        let va = vmm::USER_STACK_TOP - (p + 1) * mm::PAGE;
        if vmm::map_page(aspace, va, frame, true, true).is_err() {
            log("[proc] FATAL: stack map failed\n");
            return None;
        }
    }

    // The 16 BMO Channel estuaries, shared U/S with Ring 0.
    for i in 0..boot_context::MAX_CHANNEL_PAGES {
        let va = vmm::CHANNEL_VA_BASE + (i as u64) * mm::PAGE;
        if vmm::map_page(aspace, va, channel::page_phys(i), true, true).is_err() {
            log("[proc] FATAL: channel map failed\n");
            return None;
        }
    }

    // Kernel landing stack + fabricated Ring 3 context. The frames MUST be
    // physically contiguous: the stack is addressed linearly through the
    // physmap, and `fabricate` writes the context in the TOP page — with two
    // independent alloc_frame calls that page is `base+4K` physical, a frame
    // nobody granted us unless the allocator happened to return neighbors
    // (true on QEMU's clean map, false on real memory maps with holes; the
    // context then lives in a foreign/free frame and dies with the next
    // zero_frame — restored as zeros: backptr=0, pops to rsp=0x78, iretq
    // with cs=0 ⇒ the observed #GP(0)).
    let kstack_base = phys::alloc_frames_contig(KERNEL_STACK_PAGES)?;
    let kstack_top = mm::phys_to_virt(kstack_base) + KERNEL_STACK_PAGES * mm::PAGE;
    let context = unsafe { trap::fabricate(kstack_top, entry_va, 0, true, vmm::USER_STACK_TOP) };

    let tid = scheduler::spawn_user(1, context, kstack_base, KERNEL_STACK_PAGES, kstack_top, aspace, 0)?;
    // F3: seed the init process's capability table — one estuary handle
    // per BMO Channel page, discoverable via TASK_OP_CHANNEL_OPEN.
    crate::ring0::cap::seed_init(1);
    log("[proc] init.bex admitted: Ring 3 entry at 0x");
    crate::ring0::dev::console::serial_write_u64(entry_va, 16);
    log("\n");
    set_status("admitted");
    Some(tid)
}
