[target.x86_64-unknown-none]
rustflags = [
  "-C", "link-arg=-T",
  "-C", "link-arg=crates_Personal/mod_bmo_core/linker.ld",
  "-C", "relocation-model=static",
  "-C", "target-feature=+crt-static",
]
