[workspace]

[package]
name = "mod-wine-devour"
version = "1.0.0"
edition = "2021"
description = "BMO WINE Devourer — Windows PE/COFF to BEF runtime converter (Ring 3 module)"

[dependencies]
bmo-hal = { path = "../../../Uso_Reales_Crates/shared/bmo-hal" }
bmo-abi = { path = "../../../Uso_Reales_Crates/abi/bmo-abi" }
goblin = { path = "../../plugins/goblin", default-features = false, features = ["alloc", "elf32", "elf64", "pe32", "pe64", "endian_fd"] }
