//! AUTO-GENERATED BY SigDead Intelligence Exporter
//! DO NOT EDIT MANUALLY

pub struct RpcHandshakeStep {
    pub name: &'static str,
    pub func_id: u32,
    pub length: u32,
    pub expected_status: u32,
}

pub const GSP_RPC_HANDSHAKE: &[RpcHandshakeStep] = &[
    RpcHandshakeStep { name: "GSP_CMD_UCODE_LOAD", func_id: 0x0001, length: 512, expected_status: 0 },
    RpcHandshakeStep { name: "UNKNOWN_FUNC_4000", func_id: 0x4000, length: 1280, expected_status: 0 },
    RpcHandshakeStep { name: "UNKNOWN_FUNC_0018", func_id: 0x0018, length: 16, expected_status: 24 },
    RpcHandshakeStep { name: "UNKNOWN_FUNC_0010", func_id: 0x0010, length: 24, expected_status: 32 },
    RpcHandshakeStep { name: "UNKNOWN_FUNC_0018", func_id: 0x0018, length: 32, expected_status: 8 },
    RpcHandshakeStep { name: "GSP_CMD_DMA_COPY", func_id: 0x0008, length: 16, expected_status: 24 },
    RpcHandshakeStep { name: "UNKNOWN_FUNC_0010", func_id: 0x0010, length: 24, expected_status: 16 },
    RpcHandshakeStep { name: "UNKNOWN_FUNC_1800", func_id: 0x1800, length: 4096, expected_status: 0 },
    RpcHandshakeStep { name: "UNKNOWN_FUNC_0018", func_id: 0x0018, length: 16, expected_status: 0 },
    RpcHandshakeStep { name: "RM_CTRL_INIT", func_id: 0x0100, length: 22, expected_status: 23 },
];
