//! AUTO-GENERATED BY SigDead Intelligence Exporter
//! DO NOT EDIT MANUALLY

#[allow(dead_code)]
pub mod registers {
    /// Start CPU
    pub const CPUCTL: u32 = 0x840100;
    /// Boot vector address
    pub const BOOTVEC: u32 = 0x840104;
    /// Interrupt status
    pub const IRQSTAT: u32 = 0x840008;
    /// IMEM Control
    pub const IMEMC: u32 = 0x840180;
    /// DMEM Control
    pub const DMEMC: u32 = 0x8401C0;
    /// Engine clock gating
    pub const PMC_ENABLE: u32 = 0x000200;
}
