[package]
name = "bmo-input"
version = "0.1.0"
edition = "2021"
description = "BMO Input Subsystem — HAL-based keyboard/mouse/pointer driver with PS/2 and USB HID backends"

[lib]

[dependencies]
bmo-abi = { path = "../../../../Uso_Reales_Crates/abi/bmo-abi" }

[features]
default = ["ps2"]
ps2 = []
