[package]
name = "mod-cabina"
version = "1.0.0"
edition = "2021"
authors = ["BMO Project"]
description = "Cabina module — standalone Ring 3 telemetry/logging system loaded by bootloader"

[dependencies]
cabina-daemon = { path = "../../ring0/cabina_daemon" }
bmo-hal = { path = "../../../Uso_Reales_Crates/shared/bmo-hal" }
