//! Ring 3 process creation from BEX images (F2).
//!
//! Pipeline: BootContext payload -> `bex::inspect` (validated mapping plan)
//! -> fresh user address space -> frames copied/zeroed per section -> user
//! stack -> 16 BMO Channel estuaries mapped U/S -> fabricated Ring 3 trap
//! frame -> `scheduler::spawn_user`. The first timer tick after
//! `timer::enable()` preempts the shell and enters CPL3 via iretq.
//!
//! v1 deliberately keeps the section leaf frames alive for the whole life
//! of the system: the single init process does not exit-reclaim (that is
//! part of the EXIT hardening work, with per-task allocation lists).

use boot_context::BootContext;

use crate::ring0::task::aterrizaje;
use crate::ring0::task::bex;
use crate::ring0::obj::channel;
use crate::ring0::mm::{self, phys, vmm};
use crate::ring0::task::scheduler;
use crate::ring0::plat::trap;

const USER_STACK_PAGES: u64 = 16; // 64 KiB
/// 16 KiB de pila de kernel por tarea.
///
/// Eran 8 KiB cuando el contexto guardado ocupaba 720 bytes. Con XSAVE ocupa
/// ~3,3 KiB --el area de estado extendido es de 3072-- y cada trap se lleva eso
/// de la pila antes de que el despachador de Rust haga nada. Con 8 KiB un
/// fault anidado sobre un tick de timer se salia. El coste de subirlo son dos
/// paginas por tarea; el coste de no subirlo es corromper la pila de al lado.
const KERNEL_STACK_PAGES: u64 = 4;

// Que quepa no es una esperanza: se comprueba al compilar. Si alguien sube
// XSAVE_AREA sin tocar esto, el build se para aqui y no en el hardware.
const _: () = assert!(
    trap::MIN_TASK_STACK <= (KERNEL_STACK_PAGES * mm::PAGE) as usize,
    "la pila de kernel por tarea no cubre un contexto con XSAVE"
);

static mut TSS_PTR: u64 = 0;

/// Last outcome of `spawn_init`, kept so `phase::main` can surface it on the
/// dashboard *after* the screen is cleared (spawn_init runs before that).
static mut INIT_STATUS: &str = "not attempted";

fn set_status(s: &'static str) {
    unsafe { INIT_STATUS = s };
}

/// Human-readable result of the last `spawn_init` call, for on-screen report.
pub fn init_status() -> &'static str {
    unsafe { INIT_STATUS }
}

/// Embedded "hola mundo" Ring 3 program (generated by `toolchain/tools/hello-bex`).
/// When the boot chain reserves no Ring 3 payload, this is admitted as the
/// init process so BMO always demonstrates the full CPL3 -> INVOKE -> CPL0
/// chain on its own -- no keyboard, no storage, no external image required.
static INIT_HELLO_BEX: &[u8] = include_bytes!("../init_hello.bex");

/// Programa C compilado por `toolchain/lang/c` (fuente:
/// `toolchain/lang/c/examples/hola_C.c`).
static HOLA_C_BEX: &[u8] = include_bytes!("../hola_C.bex");

/// Programa COBOL compilado por `toolchain/lang/cobol` (fuente:
/// `toolchain/lang/cobol/examples/hola_COBOL.cob`).
static HOLA_COBOL_BEX: &[u8] = include_bytes!("../hola_COBOL.bex");
/// El par cliente/servidor de Endpoint RPC. Se regeneran con
/// `cargo run -p bmo-rpc-demo -- <srv> <cli>` y se commitean, igual que los
/// demas demos.
static RPC_SRV_BEX: &[u8] = include_bytes!("../rpc_srv.bex");
static RPC_CLI_BEX: &[u8] = include_bytes!("../rpc_cli.bex");

// * EL COMPOSITOR YA NO ESTA AQUI.
//
// Vivia en esta lista como `include_bytes!("../compositor.bex")`, y eso era la
// deuda que `fs.rs` lleva describiendo desde que existe: un binario de Ring 3
// dentro del binario de Ring 0. Cambiar un pixel del escritorio obligaba a
// recompilar el sistema operativo entero y reflashear -- y ademas metia en el
// repositorio un blob de 24 KiB que `build.ps1` reescribia en CADA build.
//
// Ahora se carga del volumen de datos, como cualquier programa. El sitio donde
// se arranca es `core::phase`, y no por capricho: **el disco todavia no esta
// montado cuando se llama a `spawn_init`**. `dev::disk::init` y `fs::mount_data`
// pasan mucho despues, asi que aqui no habria de donde leerlo.
//
// Los cinco demos de abajo SI se quedan embebidos, y eso tambien es una
// decision: son la red que demuestra la cadena CPL3 -> INVOKE -> CPL0 **sin
// depender de un disco**. El dia que el SATA no enumere, BMO tiene que poder
// seguir ensenando que Ring 3 funciona.

/// Los programas Ring 3 que BMO admite al arrancar cuando la cadena de
/// arranque no reservo ninguno.
///
/// Son TRES procesos separados, con su propio espacio de direcciones y su
/// propia tabla de capabilities. El primero es el hola-mundo en ensamblador
/// que valido la cadena CPL3 en su dia; los otros dos salen de los
/// compiladores de C y COBOL de BMO -- es la primera vez que un lenguaje de
/// alto nivel compilado aqui corre sobre el metal.
///
/// Si uno falla al admitirse, se registra y se sigue con los demas: el
/// aislamiento de fallos existe justo para que un programa malo no se lleve
/// por delante al sistema.
/// `(etiqueta corta para el log, name legible, imagen BEX)`
static DEMOS: &[(&str, &str, &[u8])] = &[
    ("asm", "init_hello (asm)", INIT_HELLO_BEX),
    ("C", "hola_C (C)", HOLA_C_BEX),
    ("COBOL", "hola_COBOL (COBOL)", HOLA_COBOL_BEX),
    // El par que prueba Endpoint RPC. El servidor va PRIMERO para que tenga
    // el primer turno y cree el endpoint; aun asi el cliente reintenta
    // cediendo el turno, porque el orden del planificador no es una garantia
    // sobre la que se pueda construir.
    ("srv", "rpc_servidor", RPC_SRV_BEX),
    ("cli", "rpc_cliente", RPC_CLI_BEX),
];

/// Capture the TSS location from the BootContext (identity-mapped).
pub fn init(ctx: &BootContext) {
    unsafe { TSS_PTR = ctx.tss_ptr };
}

/// Update TSS.RSP0: the kernel stack the CPU switches to when Ring 3 code
/// of the *current* task takes an interrupt. Called at every switch into a
/// user task.
pub fn set_tss_rsp0(top: u64) {
    let tss = unsafe { TSS_PTR };
    if tss == 0 {
        return;
    }
    unsafe {
        ((tss + 4) as *mut u32).write_volatile(top as u32);
        ((tss + 8) as *mut u32).write_volatile((top >> 32) as u32);
    }
}

fn log(msg: &str) {
    crate::ring0::dev::console::serial_write(msg);
}

/// Load the init process from the BootContext Ring 3 payload, if one was
/// reserved by the boot chain. Returns the new TID. With no payload this
/// is a no-op so boot stays exactly as before.
pub fn spawn_init(ctx: &BootContext) -> Option<u32> {
    // Un payload de la cadena de arranque manda sobre todo lo demas.
    if ctx.ring3_payload_phys != 0 && ctx.ring3_payload_size >= 48 {
        let bytes = unsafe {
            core::slice::from_raw_parts(
                mm::phys_to_virt(ctx.ring3_payload_phys) as *const u8,
                ctx.ring3_payload_size as usize,
            )
        };
        // Un payload de arranque llega ENTERO en memoria: lo que mide y lo que
        // hay son el mismo numero. Aqui no hay cargador que pueda ser selectivo.
        return admit_payload(bytes, 1, bytes.len());
    }

    // * SIN PAYLOAD EXTERNO NO SE ARRANCA NADA.
    //
    // Aqui se admitian cinco programas de ejemplo en cada arranque: el hola
    // mundo en ensamblador, el de C, el de COBOL y el par de RPC. Su trabajo
    // era demostrar que Ring 3 existia, que un `.bex` de cada lenguaje corria
    // y que dos procesos podian hablarse. **Los tres estan demostrados y
    // fotografiados**, asi que a partir de aqui no demuestran: estorban.
    //
    // Y estorbaban de verdad, no en abstracto. `init_hello` **reclama la
    // pantalla** para ensenar que Ring 3 puede pintarla; arrancaba a la vez
    // que el escritorio, ganaba, pintaba tres lineas, terminaba -- y al morir
    // el kernel recuperaba la pantalla y repintaba su panel encima del
    // escritorio recien nacido. Eso es lo que salia en cada foto y lo que
    // llevo a acusar tres veces al compositor de morirse.
    //
    // Un arranque no es una demostracion: es arrancar. Lo que se ensena es la
    // presentacion de Ring 3 y el escritorio, y punto.
    //
    // Y no se pierde nada, porque **los ejemplos viven en el disco**: se
    // lanzan a mano con `run c/holac.bex`, `run cobol/banco.bex`,
    // `run ada/cierre.bex`. Esos son ademas los de verdad -- los compilados por
    // el toolchain en cada build, no las copias congeladas dentro del kernel.
    //
    // * Al dejar de arrancarlos, los `.bex` embebidos pasaron a ser codigo
    // muerto y el enlazador se los llevo: **el kernel adelgazo 37 KB**. Ese es
    // el precio real que se estaba pagando por una demostracion ya hecha.
    log("[proc] sin payload de arranque: no se admite nada (los ejemplos van a mano)\n");
    crate::ring0::cabina::info("ring3", "sin payload: el escritorio es el unico Ring 3", 0);
    None
}

/// Los ejemplos embebidos, para lanzarlos **a mano**. Ver [`spawn_init`]: ya no
/// se arrancan solos.
#[allow(dead_code)]
fn admitir_ejemplos() -> Option<u32> {
    let mut first: Option<u32> = None;
    let mut index = 0;
    while index < DEMOS.len() {
        let (tag, name, bytes) = DEMOS[index];
        let pid = index as u32 + 1;
        // El log tiene que decir de quien es cada linea ANTES de que el
        // proceso escriba la primera.
        crate::ring0::uconsole::set_tag(pid, tag);
        // La entrada del registro se abre ANTES de intentar admitirlo: si el
        // BEX es rechazado, tiene que aparecer igual en la tabla, marcado.
        record_open(tag, name, pid, bytes.len() as u32);
        // Un `.bex` embebido esta entero en la imagen del kernel: mide lo que
        // ocupa el slice, no hay disco por medio.
        match admit_payload(bytes, pid, bytes.len()) {
            Some(tid) => {
                crate::ring0::cabina::info(name, "programa Ring 3 admitido", tid as u64);
                if first.is_none() {
                    first = Some(tid);
                }
            }
            None => {
                // Que uno no entre no puede tumbar a los demas: el
                // aislamiento de fallos existe exactamente para esto.
                crate::ring0::cabina::warn(name, "no se pudo admitir", pid as u64);
            }
        }
        index += 1;
    }
    first
}

// -- Programas que vienen del DISCO ------------------------------------------

/// Nombres de los programas cargados de disco.
///
/// `ProgramRecord` guarda `&'static str` porque los tres demos son literales
/// del binario. Un programa que llega del disco trae su nombre en un buffer
/// prestado que desaparece al volver del comando, asi que se copia aqui: un
/// almacen estatico pequeno cuya vida SI es la del kernel. Sin `alloc`, esta
/// es la forma honesta de tener un `&'static str` que no existia al compilar.
const MAX_DISK_NAMES: usize = 6;
const DISK_NAME_LEN: usize = 24;
static mut DISK_NAMES: [[u8; DISK_NAME_LEN]; MAX_DISK_NAMES] = [[0; DISK_NAME_LEN]; MAX_DISK_NAMES];
static mut DISK_NAME_COUNT: usize = 0;

fn intern_name(s: &str) -> &'static str {
    unsafe {
        // Si ya esta guardado, se reusa. Lanzar `apps/batch.bex` cinco veces
        // gastaba cinco ranuras de seis, y a la septima todos los programas se
        // llamaban "disco" en la bitacora -- que es justamente cuando hace falta
        // saber cual era.
        let arr_ro = core::ptr::addr_of!(DISK_NAMES) as *const [u8; DISK_NAME_LEN];
        for i in 0..DISK_NAME_COUNT {
            let buf = &*arr_ro.add(i);
            let n = s.len().min(DISK_NAME_LEN);
            if buf[..n] == s.as_bytes()[..n] && (n == DISK_NAME_LEN || buf[n] == 0) {
                let p = buf.as_ptr();
                if let Ok(t) = core::str::from_utf8(core::slice::from_raw_parts(p, n)) {
                    return t;
                }
            }
        }
        if DISK_NAME_COUNT >= MAX_DISK_NAMES { return "disco"; }
        let slot = DISK_NAME_COUNT;
        DISK_NAME_COUNT += 1;
        let arr = core::ptr::addr_of_mut!(DISK_NAMES) as *mut [u8; DISK_NAME_LEN];
        let buf = &mut *arr.add(slot);
        let n = s.len().min(DISK_NAME_LEN);
        buf[..n].copy_from_slice(&s.as_bytes()[..n]);
        let p = buf.as_ptr();
        core::str::from_utf8(core::slice::from_raw_parts(p, n)).unwrap_or("disco")
    }
}

/// El siguiente pid libre.
///
/// Antes el pid era el INDICE del demo en su tabla, asi que solo podian
/// existir los tres de siempre y no habia forma de anadir un cuarto. Ahora sale
/// del registro, que es quien sabe cuantos programas se han intentado admitir.
fn next_pid() -> u32 {
    unsafe {
        let p = NEXT_PID;
        NEXT_PID = NEXT_PID.wrapping_add(1).max(1);
        p
    }
}

/// Queda sitio para otro programa? **Se lo pregunta al planificador.**
///
/// * Aqui vivia el bug que dejaba la maquina sin poder lanzar nada. Esto era
/// `PROGRAM_COUNT < MAX_PROGRAMS`, o sea la longitud del REGISTRO HISTORICO de
/// abajo -- una bitacora de ocho entradas que a proposito no baja nunca, porque
/// apunta tambien los programas que se rechazaron. El arranque gasta seis
/// (cinco demos mas el compositor), asi que al tercer `run` la maquina decia
/// "sin hueco" y no volvia a admitir un programa hasta reiniciar. Y no era
/// mentira a medias: habia 58 ranuras de tarea libres.
///
/// La capacidad viva la tiene el planificador, que recicla la ranura cuando
/// `reap` recoge una tarea terminada. Un registro cuenta lo que PASO; solo el
/// planificador sabe lo que HAY.
pub fn has_room() -> bool {
    crate::ring0::task::scheduler::hay_hueco()
}

/// Admite un programa BEX que viene de un archivo, no del propio binario.
///
/// Es la razon de ser de todo el trabajo de disco: hasta aqui los programas
/// Ring 3 viajaban dentro del kernel con `include_bytes!` y cambiar una linea
/// de un `hola mundo` obligaba a recompilar el sistema operativo y reflashear.
///
/// Devuelve `(tid, pid)`. El pid hace falta para encauzar la salida del
/// hijo a la consola de quien lo lanzo (ver `ring0/consola.rs`).
/// `tam_fichero` es lo que mide el archivo EN EL DISCO, que desde el escalon 2
/// **ya no es `bytes.len()`**: el cargador trae solo lo que se ejecuta. Los dos
/// numeros se pasan por separado porque contestan preguntas distintas -- ver la
/// nota de los dos limites en `bex::inspect`.
pub fn admit_from_disk(name: &str, bytes: &[u8], tam_fichero: usize) -> Option<(u32, u32)> {
    if !has_room() { return None; }
    let pid = next_pid();
    let stored = intern_name(name);
    // La etiqueta del log ANTES de que el proceso escriba su primera linea,
    // igual que con los demos: si no, la primera linea sale sin dueno.
    crate::ring0::uconsole::set_tag(pid, stored);
    // Se apunta lo que MIDE, no lo que se trajo: el panel dice de que tamano es
    // el programa, y eso no cambia porque el cargador sea mas listo.
    record_open(stored, stored, pid, tam_fichero as u32);
    match admit_payload(bytes, pid, tam_fichero) {
        Some(tid) => {
            crate::ring0::cabina::info("proc", "programa admitido DESDE DISCO", tid as u64);
            Some((tid, pid))
        }
        None => {
            crate::ring0::cabina::warn("proc", "el .bex de disco no paso la admision", pid as u64);
            None
        }
    }
}

/// La imagen ya esta ENTERA en RAM. Es el camino de las que el kernel embebe con
/// `include_bytes!` --no hay disco del que pedirlas-- y el de ESTRATOS mientras su
/// gate siga hasheando el fichero completo.
fn admit_payload(bytes: &[u8], pid: u32, tam_fichero: usize) -> Option<u32> {
    admit_payload_desde(bytes, &mut Origen::EnMemoria(bytes), pid, tam_fichero)
}

/// **Admite un programa PIDIENDOLE LOS BYTES AL DISCO, sin mesa.**
///
/// `prologo` son los primeros bytes --cabecera y tabla de secciones-- que es
/// todo lo que hace falta para hacer el plan. Cada seccion se pide despues por su
/// rango y **cae directamente en los marcos de su proceso**.
///
/// Es el gemelo de [`admit_from_disk`] y comparte con el todo menos de donde
/// salen los bytes. Ver [`Origen`].
pub fn admitir_por_rangos(
    name: &str,
    prologo: &[u8],
    fuente: &mut crate::ring0::task::lanzar::Fuente,
    tam_fichero: usize,
) -> Option<(u32, u32)> {
    if !has_room() {
        return None;
    }
    let pid = next_pid();
    let stored = intern_name(name);
    crate::ring0::uconsole::set_tag(pid, stored);
    record_open(stored, stored, pid, tam_fichero as u32);
    let mut origen = Origen::PorRangos(fuente);
    match admit_payload_desde(prologo, &mut origen, pid, tam_fichero) {
        Some(tid) => {
            crate::ring0::cabina::info("proc", "programa admitido SIN MESA", tid as u64);
            Some((tid, pid))
        }
        None => {
            crate::ring0::cabina::warn("proc", "el .bex de disco no paso la admision", pid as u64);
            None
        }
    }
}

/// **DE DONDE SALEN LOS BYTES DE UNA SECCION.** Un cargador, dos origenes.
///
/// === La pieza B, y por que es un enum y no dos funciones ===
///
/// El cargador traia el fichero a una mesa de 4 MiB y copiaba de ahi a las
/// paginas del proceso. La mesa era **una y de toda la maquina**, con un tope
/// decidido de antemano que hubo que subir dos veces, y con una copia por cada
/// byte de cada programa.
///
/// `PorRangos` la borra: el HBA escribe **en el marco del proceso**, que es el
/// destino final. Cero copias, cero mesa, y el tope de un programa pasa a ser la
/// RAM que hay.
///
/// `EnMemoria` se queda porque hay dos casos que de verdad ya estan en RAM: las
/// imagenes que el kernel **embebe** (`include_bytes!`, no hay disco del que
/// leerlas) y ESTRATOS, cuyo gate hashea el fichero entero de una pasada. Ver la
/// nota de `Fuente::rango`.
///
/// Que sean dos variantes del MISMO camino --y no dos cargadores-- es lo que
/// impide que se separen: el bucle que reserva marcos, aplica relocations,
/// cierra hashes y mapea es **uno**, y lo unico que cambia es de donde viene el
/// trozo.
pub enum Origen<'a> {
    /// La imagen entera, ya en RAM.
    EnMemoria(&'a [u8]),
    /// Se pide al disco por rangos. **Sin mesa.**
    PorRangos(&'a mut crate::ring0::task::lanzar::Fuente),
}

impl Origen<'_> {
    /// Trae `dst.len()` bytes de la imagen desde `offset`. Devuelve cuantos.
    fn traer(&mut self, offset: usize, dst: &mut [u8]) -> usize {
        match self {
            Origen::EnMemoria(bytes) => {
                let fin = offset.saturating_add(dst.len()).min(bytes.len());
                if offset >= fin {
                    return 0;
                }
                let n = fin - offset;
                dst[..n].copy_from_slice(&bytes[offset..fin]);
                n
            }
            Origen::PorRangos(f) => f.rango(offset, dst),
        }
    }

    /// **Trae un rango SUELTO: no forma parte del flujo de secciones.**
    ///
    /// Lo usan las dos tablas que el cargador necesita **antes** de aterrizar
    /// nada --los hashes y las relocations-- y que viven **al final del
    /// fichero**. Por `traer` las pediria el cursor secuencial, que se iria al
    /// final y ya no podria volver al codigo: solo avanza, a proposito.
    ///
    /// Ver `lanzar::Fuente::rango_suelto`, que es donde esta contado entero.
    fn traer_suelto(&mut self, offset: usize, dst: &mut [u8]) -> usize {
        match self {
            // En memoria no hay cursor que mover: es la misma lectura.
            Origen::EnMemoria(_) => self.traer(offset, dst),
            Origen::PorRangos(f) => f.rango_suelto(offset, dst),
        }
    }
}

/// Lo mas grande que puede medir una seccion `Signature`, **segun el formato**.
///
/// No es un numero inventado como lo era `MAX_BEX`: la cabecera son 8 bytes y hay
/// como mucho una entrada de 40 por seccion, con `MAX_BEX_SECTIONS` de tope. Un
/// limite que sale del contrato no hay que subirlo nunca.
const MAX_FIRMA: usize = 8 + bex::MAX_BEX_SECTIONS * 40;

/// Admite UN programa BEX como proceso Ring 3 con el `pid` indicado.
///
/// `prologo` son los primeros bytes de la imagen: la cabecera y la tabla de
/// secciones, que es todo lo que hace falta para hacer el plan. **El resto ya no
/// se trae de antemano** -- se pide por `origen` seccion a seccion, y cada una
/// cae directamente en los marcos de su proceso.
fn admit_payload_desde(
    prologo: &[u8],
    origen: &mut Origen,
    pid: u32,
    tam_fichero: usize,
) -> Option<u32> {
    let bytes = prologo;
    set_status("admitting (alloc/map)");
    let plan = match bex::inspect(bytes, tam_fichero) {
        Ok(p) => p,
        Err(e) => {
            // ** EL MOTIVO, CON SU NOMBRE. Aqui habia un `Err(_)`.
            //
            // Trece motivos distintos entraban por esta puerta y salian con la
            // misma frase: *"payload failed BEX admission"*. Un cargador que
            // sabe por que rechaza y no lo dice obliga a adivinar entre "el
            // fichero llego a medias", "otra arquitectura" y "el entry cae
            // fuera" -- tres cosas que se arreglan en tres sitios que no se
            // parecen en nada. Costo una tanda de fotos el 2026-08-09.
            //
            // Se dicen ademas **los bytes que llegaron**, porque el fallo mas
            // probable de los trece es justo el que se cuenta con un numero.
            log("[proc] FATAL: payload failed BEX admission\n");
            crate::ring0::cabina::fault("proc", e.name(), bytes.len() as u64);
            // ** Y LA PRUEBA DE LA ACUSACION: los ocho primeros bytes.
            //
            // Decir *"cabecera invalida"* es una afirmacion, y su evidencia son
            // ocho bytes. Sin ellos hay que **reproducir el fallo para
            // entenderlo**, que el 2026-08-10 fueron dos tandas de fotos y una
            // tarde entre cuatro hipotesis que se distinguen a simple vista:
            //
            // | lo que salga | quiere decir |
            // |---|---|
            // | `00 00 00 00...` | el DMA escribio en otro sitio |
            // | bytes del medio del fichero | llego el sector equivocado |
            // | algo que no es ni una cosa ni otra | el LBA esta mal |
            // | `...31464542` (BEF1 corrido) | un desfase, no una corrupcion |
            //
            // No es una linea de depuracion que se quita: **un error que no
            // puede ensenar su evidencia es un error a medias**, y este camino
            // --el prologo de una imagen que viene del disco-- es justo donde
            // menos se puede permitir adivinar.
            let mut ocho = [0u8; 8];
            let n = bytes.len().min(8);
            ocho[..n].copy_from_slice(&bytes[..n]);
            crate::ring0::cabina::fault(
                "proc",
                "los 8 primeros bytes de lo que llego",
                u64::from_le_bytes(ocho),
            );
            set_status("BEX admission failed");
            return None;
        }
    };
    // ** LOS `?` DE AQUI ABAJO ERAN MUDOS, y ese era el ultimo hueco.
    //
    // El 2026-08-11 se le dio nombre a diez caminos de fallo que hablaban por el
    // klog. Quedaban estos seis, que no hablaban **en absoluto**: un `?` sobre
    // un `Option` devuelve `None` y se acabo. Desde fuera, un `.bex` rechazado
    // por falta de memoria y uno rechazado por un hash malo se ven igual.
    let Some(aspace) = vmm::new_address_space() else {
        crate::ring0::cabina::fault("proc", "sin memoria para el espacio de direcciones", 0);
        return None;
    };

    // Sections: assigned sequentially from USER_IMAGE_BASE, honoring each
    // section's alignment. entry_offset is relative to the Code section.
    // * PASE 1: DONDE VA CADA SECCION, sin reservar ni un marco.
    //
    // Hacia falta partir el bucle en dos, y el motivo es concreto: una
    // relocation dice *"en `.data`+8 escribe la direccion de `.rodata`+17"*, y
    // eso no se puede resolver hasta conocer las VA de **todas** las secciones.
    // Antes se calculaba la VA y se copiaba y mapeaba en la misma vuelta, asi
    // que al llegar a `.data` la de `.rodata` ya se habia perdido.
    //
    // La cuenta es la de siempre y no cambia --alinear, tantas paginas como pida
    // `mem_size`, y la siguiente empieza tras ellas--, solo se hace antes.
    let mut va_de = [0u64; bex::MAX_BEX_SECTIONS];
    {
        let mut va_cursor = vmm::USER_IMAGE_BASE;
        for i in 0..plan.section_count {
            let s = plan.sections[i];
            let align = s.alignment as u64;
            va_cursor = (va_cursor + align - 1) & !(align - 1);
            va_de[i] = va_cursor;
            let pages = (s.mem_size + mm::PAGE - 1) / mm::PAGE;
            va_cursor = va_cursor + pages * mm::PAGE;
        }
    }

    // La VA de una seccion por su CODIGO DE RELOCATION (`0` = code, `1` = data,
    // `2` = rodata), que **no** es el de `SECTION_*`. La traduccion se hace aqui,
    // en un solo sitio, porque es exactamente donde se cruzarian las dos
    // numeraciones.
    let va_por_codigo_reloc = |cod: u8| -> Option<u64> {
        let buscado = match cod {
            0 => bex::SECTION_CODE,
            1 => bex::SECTION_DATA,
            2 => bex::SECTION_RODATA,
            _ => return None,
        };
        for i in 0..plan.section_count {
            if plan.sections[i].kind == buscado {
                return Some(va_de[i]);
            }
        }
        None
    };

    // ** LOS DIGESTS DECLARADOS, localizados UNA vez.
    //
    // `inspect` ya no comprueba hashes: dice donde estan. La comprobacion la
    // hace el bucle de abajo, seccion por seccion y en el momento en que cada
    // una termina de caer en la memoria del proceso. Ver `task/aterrizaje.rs`.
    //
    // Si la imagen no trae firma --las que el kernel EMBEBE no pasan por el
    // escritor-- esto es `None` y cada cierre contesta `SinFirma`. Se cuenta,
    // pero no se rechaza: exigirle una prueba a quien nunca la prometio seria
    // dejar de arrancar.
    let mut buf_firma = [0u8; MAX_FIRMA];
    let firmas = if plan.firma_file_size > 0 && plan.firma_file_size as usize <= MAX_FIRMA {
        let n = plan.firma_file_size as usize;
        // ** SUELTA, y ese detalle es la diferencia entre arrancar y no.
        //
        // La seccion `Signature` esta **al final del fichero** --en `gui.bex`, en
        // el 0x4B680 de 0x4B728-- y esto corre ANTES de aterrizar la primera
        // seccion, que empieza en el 0x200. Por el cursor del flujo, este salto
        // lo dejaria en el final y el codigo quedaria detras: `leer_en`
        // contestaria `0` --correctamente, solo avanza-- y el cargador lo diria
        // como `una seccion se quedo a medias al aterrizar =0`, que manda a
        // mirar el disco cuando el disco esta bien.
        let leidos = origen.traer_suelto(plan.firma_file_offset as usize, &mut buf_firma[..n]);
        if leidos != n {
            crate::ring0::cabina::fault("proc", "la tabla de hashes se quedo sin leer", leidos as u64);
            return None;
        }
        aterrizaje::Firmas::abrir(&buf_firma[..n], plan.firma_indice)
    } else {
        None
    };
    let mut sin_firma = 0usize;

    // * PASE 2: reservar, copiar, CERRAR, PARCHEAR y mapear.
    let mut entry_va: u64 = 0;
    let mut code_bytes: u32 = 0;
    let total_relocs = bex::cuantas_relocs(plan.relocs_file_size);

    // ** Y LA TABLA DE RELOCATIONS TAMBIEN SE CIERRA, antes de aplicar ni una.
    //
    // No se mapea, asi que no cae en el bucle de abajo -- y es la seccion cuya
    // corrupcion hace mas dano en silencio: una reloc torcida escribe un puntero
    // inventado dentro de `.data` y el proceso arranca, corre, y muere mucho
    // despues en un sitio que no se parece a la causa. Comprobarla DESPUES de
    // aplicarla no serviria de nada.
    // ** LA TABLA DE RELOCATIONS, EN MARCOS PRESTADOS.
    //
    // No se mapea en el proceso --el programa nunca la ve-- pero hay que tenerla
    // entera en RAM mientras se aplica: cada pagina pregunta por TODAS las
    // relocs, y pedirlas al disco de 24 en 24 bytes serian mil lecturas por
    // pagina.
    //
    // Se piden marcos por su tamano REAL en vez de reservar un maximo. En DOOM
    // son 30.840 bytes --ocho marcos-- que se sueltan en cuanto se aplican. Es
    // el modelo quirofano: entra lo que hace falta para la operacion en curso.
    //
    // [!] Se sueltan por el camino BUENO. Los caminos de error de aqui abajo
    // devuelven `None` sin soltarlos -- igual que ya hacen con el espacio de
    // direcciones, que tampoco se destruye. Es una fuga que solo ocurre cuando un
    // programa NO arranca, y esta apuntada para limpiarla junto con la otra: son
    // el mismo arreglo.
    let mut relocs_marcos: Option<(u64, u64)> = None;
    let relocs: &[u8] = if total_relocs > 0 {
        let n = plan.relocs_file_size as usize;
        let paginas = ((n as u64) + mm::PAGE - 1) / mm::PAGE;
        // ** EL SOSPECHOSO DE DOOM, y por eso lleva el numero puesto.
        //
        // Son marcos **CONTIGUOS**, y eso puede fallar con RAM de sobra si el
        // asignador esta fragmentado. `ray.bex` pide UNO --sus relocs son 24
        // bytes-- y DOOM pide OCHO: 30.840 bytes de tabla. Es la diferencia mas
        // grande entre el que arranca y el que no.
        let Some(base) = phys::alloc_frames_contig(paginas) else {
            crate::ring0::cabina::fault(
                "proc",
                "no hay marcos CONTIGUOS para la tabla de relocs (paginas pedidas)",
                paginas,
            );
            return None;
        };
        relocs_marcos = Some((base, paginas));
        let dst = unsafe {
            core::slice::from_raw_parts_mut(mm::phys_to_virt(base) as *mut u8, n)
        };
        // Suelta por lo mismo que la de hashes: la tabla va detras de todo lo
        // que se ejecuta, y esto corre antes de aterrizar nada.
        let leidos = origen.traer_suelto(plan.relocs_file_offset as usize, dst);
        if leidos != n {
            crate::ring0::cabina::fault("proc", "la tabla de relocs se quedo sin leer", leidos as u64);
            return None;
        }
        let esperado = firmas.as_ref().and_then(|f| f.digest_de(plan.relocs_indice));
        let mut cierre = aterrizaje::Aterrizaje::abrir(bex::SECTION_RELOCS, esperado);
        cierre.trozo(dst);
        match cierre.cerrar() {
            Ok(aterrizaje::Cierre::Cuadra) => {}
            Ok(aterrizaje::Cierre::SinFirma) => sin_firma += 1,
            Err(_) => {
                set_status("relocs corruptas");
                crate::ring0::cabina::fault(
                    "proc",
                    "el HASH de la tabla de relocs NO cuadra",
                    plan.relocs_file_size,
                );
                return None;
            }
        }
        unsafe { core::slice::from_raw_parts(mm::phys_to_virt(base) as *const u8, n) }
    } else {
        &[]
    };
    let mut aplicadas = 0usize;
    // ** EL ORDEN DE ATERRIZAJE: POR OFFSET DE FICHERO, no por direccion virtual.
    //
    // === Hoy no cambia nada. Manana lo decide todo ===
    //
    // Mientras las secciones se copien de un bufer que ya esta entero en RAM, el
    // orden da igual: `copy_nonoverlapping` va a donde le digan. Por eso esto se
    // decide **ahora**, con la prueba de que no rompe nada, y no despues.
    //
    // Con la pieza B --el disco escribiendo en los marcos del proceso-- deja de
    // dar igual: un fichero se lee hacia adelante, y el cursor de FAT32 es el
    // CLUSTER. Aterrizar en orden de VA puede pedir retroceder, y retroceder es
    // volver a recorrer la cadena desde el principio: cuadratico, y justo en el
    // caso que B existe para arreglar.
    //
    // La colocacion en memoria NO se toca -- `va_de[]` se calculo en el pase 1 y
    // sigue mandando. Lo unico que se ordena es en que orden se rellenan.
    let mut orden = [0usize; bex::MAX_BEX_SECTIONS];
    for i in 0..plan.section_count {
        orden[i] = i;
    }
    // Insercion, que para dieciseis como mucho es lo correcto: sin recursion,
    // sin memoria extra, y estable -- dos secciones con el mismo offset (solo la
    // `Bss`, que no ocupa fichero) conservan el orden del plan.
    for a in 1..plan.section_count {
        let mut b = a;
        while b > 0
            && plan.sections[orden[b - 1]].file_offset > plan.sections[orden[b]].file_offset
        {
            orden.swap(b - 1, b);
            b -= 1;
        }
    }

    for paso in 0..plan.section_count {
        let i = orden[paso];
        let s = plan.sections[i];
        let va_start = va_de[i];
        let pages = (s.mem_size + mm::PAGE - 1) / mm::PAGE;
        let writable = s.flags & bex::SECTION_FLAG_EXEC == 0;
        // ** EL CIERRE DE ESTA SECCION, abierto antes de su primer byte.
        //
        // Se busca su digest por `s.indice` --el indice en la tabla del
        // FICHERO-- y no por `i`, que es el de este plan y solo cuenta lo
        // cargable. Ver la nota de `BexMapping::indice`.
        let mut cierre =
            aterrizaje::Aterrizaje::abrir(s.kind, firmas.as_ref().and_then(|f| f.digest_de(s.indice)));
        // **Lo que le falta a una relocation partida en la frontera de pagina.**
        // `(valor, cuantos bytes ya se escribieron)`. Ver la nota larga abajo.
        //
        // Vive por SECCION y no por proceso a proposito: una seccion empieza en
        // su propia VA, asi que una cola que sobreviviera al final de una
        // seccion se escribiria al principio de OTRA -- ocho bytes en el sitio
        // equivocado, y el programa arrancando con basura donde va un puntero.
        let mut cola: Option<(u64, usize)> = None;
        for p in 0..pages {
            let Some(frame) = phys::alloc_frame() else {
                crate::ring0::cabina::fault(
                    "proc",
                    "sin marcos libres para una pagina de seccion",
                    va_start + p * mm::PAGE,
                );
                return None;
            };
            phys::zero_frame(frame);
            let chunk = p * mm::PAGE;
            if chunk < s.file_size {
                let n = (s.file_size - chunk).min(mm::PAGE) as usize;
                unsafe {
                    // ** AQUI MURIO LA COPIA (2026-08-10, pieza B).
                    //
                    // Esto era un `copy_nonoverlapping` desde una mesa de 4 MiB
                    // que antes habia que llenar entera desde el disco. Ahora
                    // `dst` **es el marco**, y `traer` le pide al origen justo
                    // este rango: con `PorRangos`, el HBA escribe ahi y el byte
                    // no pasa por ningun sitio intermedio.
                    //
                    // > La RAM no es una bodega. Y ahora tampoco es una cinta
                    // > transportadora.
                    let dst = core::slice::from_raw_parts_mut(
                        mm::phys_to_virt(frame) as *mut u8,
                        n,
                    );
                    let leidos = origen.traer((s.file_offset + chunk) as usize, dst);
                    if leidos != n {
                        // Una seccion que llega a medias NO se rellena con lo que
                        // hubiera: se dice cuanto falto. El marco ya estaba a
                        // cero, asi que lo que no llego son ceros y no basura de
                        // otro -- pero eso no lo convierte en valido.
                        crate::ring0::cabina::fault(
                            "proc",
                            "una seccion se quedo a medias al aterrizar",
                            leidos as u64,
                        );
                        return None;
                    }
                    // ** SE LE DA AL HASHER LO QUE HAY EN EL MARCO, no lo que
                    // habia en el origen.
                    //
                    // Es toda la diferencia entre esta comprobacion y la que
                    // habia antes. Leerlo de `bytes` certificaria que el bufer
                    // era bueno; leerlo de aqui certifica **lo que este proceso
                    // va a ejecutar**, que es lo unico que importa -- y de paso
                    // cubre la copia, que es un sitio donde las cosas se rompen.
                    //
                    // Y son `n` bytes, no la pagina: el relleno de ceros del
                    // final no es parte de la seccion, y meterlo cambiaria el
                    // hash de toda imagen que no acabe en frontera de pagina.
                    cierre.trozo(core::slice::from_raw_parts(
                        mm::phys_to_virt(frame) as *const u8,
                        n,
                    ));
                }
            }
            // * LAS RELOCATIONS QUE CAEN EN ESTA PAGINA.
            //
            // Se parchea AQUI, con el marco todavia alcanzable por
            // `phys_to_virt` y ANTES de mapearlo: asi no hay que caminar las
            // tablas del proceso para escribir en su memoria, ni dejar una
            // pagina escribible que luego habria que volver a proteger.
            let pagina_va = va_start + p * mm::PAGE;
            // ** LA COLA DE LA PAGINA ANTERIOR, ANTES QUE NADA.
            //
            // Si una relocation se partio en la frontera, lo que le falta se
            // escribe aqui: al principio de este marco, que es literalmente el
            // byte siguiente al ultimo de la pagina de antes. Va lo PRIMERO
            // porque los bytes de la seccion ya estan puestos y una relocation
            // manda sobre ellos.
            if let Some((valor, ya)) = cola.take() {
                let quedan = 8 - ya;
                unsafe {
                    let dst = mm::phys_to_virt(frame) as *mut u8;
                    core::ptr::copy_nonoverlapping(
                        valor.to_le_bytes().as_ptr().add(ya),
                        dst,
                        quedan,
                    );
                }
            }
            for r in 0..total_relocs {
                // De `relocs`, que es la tabla que se acaba de traer a sus
                // marcos -- y con offset **0**, porque ese slice empieza donde
                // empieza la tabla. Leerla de `bytes` era leerla de la imagen
                // entera, y desde la pieza B `bytes` es solo el prologo: la tabla
                // de DOOM (30.840 B) cae mucho mas alla y no habria ni una reloc
                // que aplicar.
                let Some(rel) = bex::leer_reloc(relocs, 0, plan.relocs_file_size, r) else {
                    log("[proc] FATAL: tabla de relocations mal formada\n");
                crate::ring0::cabina::fault("proc", "la tabla de relocations esta mal formada", r as u64);
                    return None;
                };
                if rel.kind != bex::RELOC_SECCION_ABS64 {
                    // Aplicar una reloc que no se entiende seria escribir un
                    // numero inventado en la memoria de un proceso. Se rechaza
                    // el programa entero.
                    log("[proc] FATAL: tipo de relocation desconocido\n");
                crate::ring0::cabina::fault("proc", "tipo de relocation DESCONOCIDO", rel.kind as u64);
                    return None;
                }
                let (Some(base_donde), Some(base_destino)) = (
                    va_por_codigo_reloc(rel.donde_sec),
                    va_por_codigo_reloc(rel.destino_sec),
                ) else {
                    log("[proc] FATAL: relocation a una seccion que no existe\n");
                crate::ring0::cabina::fault("proc", "relocation a una seccion que NO EXISTE", ((rel.donde_sec as u64) << 8) | rel.destino_sec as u64);
                    return None;
                };
                let donde_va = base_donde.wrapping_add(rel.donde_off);
                // No cae en esta pagina: no es cosa de esta vuelta.
                if donde_va < pagina_va || donde_va >= pagina_va + mm::PAGE {
                    continue;
                }
                let valor = (base_destino as i64).wrapping_add(rel.destino_off) as u64;
                let dentro = (donde_va - pagina_va) as usize;
                let caben = (mm::PAGE as usize) - dentro;
                unsafe {
                    let dst = (mm::phys_to_virt(frame) as *mut u8).add(dentro);
                    core::ptr::copy_nonoverlapping(
                        valor.to_le_bytes().as_ptr(),
                        dst,
                        caben.min(8),
                    );
                }
                // ** UN PUNTERO PARTIDO ENTRE DOS PAGINAS: SE ESCRIBE EN DOS
                // TROZOS, y esto es un arreglo que trajo el metal.
                //
                // === Lo que decia este sitio, y por que era falso ===
                //
                // Aqui habia un rechazo, con este motivo escrito:
                //
                // > *"No puede pasar --los punteros van alineados a 8 y la
                // > pagina es multiplo de 8-- pero se comprueba en vez de
                // > confiarlo."*
                //
                // La comprobacion estaba bien puesta. **La suposicion no.** El
                // 2026-08-11, DOOM en el Ryzen:
                //
                // ```text
                //    FALLO proc: relocation PARTIDA entre dos paginas =1074388988
                // ```
                //
                // `1074388988` es `0x4009DFFC`: offset **4092** dentro de su
                // pagina. Ocho bytes desde ahi se salen por cuatro. Y no esta
                // alineado a 8 porque **nadie lo garantizo nunca**: el codegen
                // coloca los punteros donde caen en su seccion, y con 1.285
                // relocations repartidas por 800 KB, que ninguna caiga en los
                // ultimos siete bytes de una pagina es una loteria que DOOM
                // perdio.
                //
                // > **Un "no puede pasar" con una razon al lado es una hipotesis.
                // > Esta aguanto hasta el primer programa grande.**
                //
                // === Por que basta con UNA ranura ===
                //
                // Dos relocations no pueden partir la misma frontera: se
                // solaparian, y eso ya seria un fichero corrupto. Asi que como
                // mucho hay una pendiente por pagina, y llevarla es un `Option`.
                //
                // Las paginas se recorren **en orden** (`for p in 0..pages`), asi
                // que la siguiente vuelta escribe la cola en el marco nuevo antes
                // de tocar nada mas.
                if caben < 8 {
                    cola = Some((valor, caben));
                }
                aplicadas += 1;
            }
            if vmm::map_page(aspace, pagina_va, frame, true, writable).is_err() {
                log("[proc] FATAL: section map failed\n");
                crate::ring0::cabina::fault(
                    "proc",
                    "no se pudo mapear una pagina de seccion",
                    pagina_va,
                );
                return None;
            }
        }
        // ** Y SI LA COLA SOBREVIVE A LA SECCION, eso SI es un fichero malo.
        //
        // Significa que una relocation empieza dentro de la ultima pagina y
        // acaba fuera de la seccion. No hay marco siguiente donde escribirla, y
        // sobre todo: apunta a memoria que no es suya. Se rechaza con su nombre
        // en vez de escribir los bytes que quepan y dejar medio puntero puesto.
        if cola.is_some() {
            crate::ring0::cabina::fault(
                "proc",
                "una relocation se sale por el FINAL de su seccion",
                va_start + pages * mm::PAGE,
            );
            return None;
        }
        // ** Y SE CIERRA, con la seccion entera ya en la memoria del proceso.
        //
        // Aqui --y no al final del bucle de todas-- porque el numero que hace
        // falta es CUAL fallo. Cerrarlas todas juntas al final daria "algo no
        // cuadra" cuando ya hay tres secciones mapeadas y ninguna pista de por
        // donde empezar a mirar.
        match cierre.cerrar() {
            Ok(aterrizaje::Cierre::Cuadra) => {}
            Ok(aterrizaje::Cierre::SinFirma) => sin_firma += 1,
            Err(_) => {
                // ** ESTO ERA MUDO PARA CABINA, y era el sospechoso principal.
                //
                // `set_status` escribe en el panel del kernel, que mientras el
                // compositor tiene la pantalla **no se pinta**. O sea que el
                // motivo mas probable de que un `.bex` firmado no arranque se
                // decia justo donde nadie podia leerlo, y desde fuera se veia
                // como `el .bex no paso la admision` a secas.
                set_status("una seccion no cuadra con su hash");
                crate::ring0::cabina::fault(
                    "proc",
                    "el HASH de una seccion NO cuadra: la imagen que llego no es la firmada",
                    s.kind as u64,
                );
                return None;
            }
        }
        if s.kind == bex::SECTION_CODE {
            entry_va = va_start + plan.entry_offset;
        }
        code_bytes = code_bytes.saturating_add(s.mem_size as u32);
    }
    // ** CUANTO DE LA IMAGEN QUEDO SIN CUBRIR, dicho en voz alta.
    //
    // No es un fallo --una imagen embebida no promete hashes-- pero callarlo
    // convertiria "verificado" en una palabra que a veces no significa nada. Si
    // esto sube en un `.bex` que SI paso por el escritor, es que el escritor
    // dejo de firmar algo y nadie se habria enterado.
    if sin_firma > 0 {
        crate::ring0::cabina::info("proc", "secciones sin hash con el que comparar", sin_firma as u64);
    }
    // ** Y LOS MARCOS DE LAS RELOCATIONS SE SUELTAN. Ya se aplicaron: la tabla
    // no es memoria del programa y no tiene por que sobrevivirle ni un tick.
    //
    // Es el modelo quirofano en pequeno -- entro lo que hacia falta para la
    // operacion, y sale cuando termina. En DOOM son ocho marcos; en un `.bex`
    // sin punteros que rellenar, ninguno.
    if let Some((base, paginas)) = relocs_marcos {
        for p in 0..paginas {
            phys::free_frame(base + p * mm::PAGE);
        }
    }
    // * Y SE COMPRUEBA QUE SE APLICARON TODAS.
    //
    // Una reloc que no cae en ninguna pagina es una que apunta fuera de su
    // seccion, y su sintoma seria un puntero a cero -- o sea el bug que todo esto
    // existe para matar, otra vez y en silencio. Mejor no arrancar.
    if aplicadas != total_relocs {
        log("[proc] FATAL: quedaron relocations sin aplicar\n");
        crate::ring0::cabina::warn("proc", "relocs sin aplicar", (total_relocs - aplicadas) as u64);
        return None;
    }
    if entry_va == 0 {
        log("[proc] FATAL: no entry point\n");
                crate::ring0::cabina::fault("proc", "el .bex no declara punto de entrada", 0);
        return None;
    }

    // User stack (64 KiB) just below USER_STACK_TOP.
    for p in 0..USER_STACK_PAGES {
        let Some(frame) = phys::alloc_frame() else {
            crate::ring0::cabina::fault("proc", "sin marcos libres para la pila de usuario", p);
            return None;
        };
        phys::zero_frame(frame);
        let va = vmm::USER_STACK_TOP - (p + 1) * mm::PAGE;
        if vmm::map_page(aspace, va, frame, true, true).is_err() {
            log("[proc] FATAL: stack map failed\n");
                crate::ring0::cabina::fault("proc", "no se pudo mapear la pila del proceso", va);
            return None;
        }
    }

    // The 16 BMO Channel estuaries, shared U/S with Ring 0.
    for i in 0..boot_context::MAX_CHANNEL_PAGES {
        let va = vmm::CHANNEL_VA_BASE + (i as u64) * mm::PAGE;
        if vmm::map_page(aspace, va, channel::page_phys(i), true, true).is_err() {
            log("[proc] FATAL: channel map failed\n");
                crate::ring0::cabina::fault("proc", "no se pudo mapear la pagina de canal", va);
            return None;
        }
    }

    // Kernel landing stack + fabricated Ring 3 context. The frames MUST be
    // physically contiguous: the stack is addressed linearly through the
    // physmap, and `fabricate` writes the context in the TOP page -- with two
    // independent alloc_frame calls that page is `base+4K` physical, a frame
    // nobody granted us unless the allocator happened to return neighbors
    // (true on QEMU's clean map, false on real memory maps with holes; the
    // context then lives in a foreign/free frame and dies with the next
    // zero_frame -- restored as zeros: backptr=0, pops to rsp=0x78, iretq
    // with cs=0 => the observed #GP(0)).
    let Some(kstack_base) = phys::alloc_frames_contig(KERNEL_STACK_PAGES) else {
        crate::ring0::cabina::fault(
            "proc",
            "no hay marcos CONTIGUOS para la pila de kernel de la tarea",
            KERNEL_STACK_PAGES,
        );
        return None;
    };
    let kstack_top = mm::phys_to_virt(kstack_base) + KERNEL_STACK_PAGES * mm::PAGE;
    let context = unsafe { trap::fabricate(kstack_top, entry_va, 0, true, vmm::USER_STACK_TOP) };

    let tid = scheduler::spawn_user(pid, context, kstack_base, KERNEL_STACK_PAGES, kstack_top, aspace, 0)?;
    // F3: seed the init process's capability table -- one estuary handle
    // per BMO Channel page, discoverable via TASK_OP_CHANNEL_OPEN.
    crate::ring0::obj::cap::seed_init(pid);
    log("[proc] init.bex admitted: Ring 3 entry at 0x");
    crate::ring0::dev::console::serial_write_u64(entry_va, 16);
    log("\n");
    set_status("admitted");
    // Anotar lo que el BEX declaraba: el registro de programas se llena aqui,
    // con los datos del plan de carga que acabamos de honrar.
    unsafe {
        if let Some(r) = record_mut(pid) {
            r.tid = tid;
            r.sections = plan.section_count as u8;
            r.entry_va = entry_va;
            r.code_bytes = code_bytes;
            r.admitted = true;
        }
    }
    Some(tid)
}

// -- Registro de programas ---------------------------------------------------
//
// Que se admitio, de que tamano, donde entra y con que pid. El log cuenta la
// historia segun pasa; esto es la FOTO: una tabla que se puede mirar despues,
// cuando las lineas del log ya rodaron y desaparecieron.

/// Un programa BEX que el kernel intento admitir.
#[derive(Clone, Copy)]
pub struct ProgramRecord {
    /// Etiqueta corta con la que sale en el log ("asm", "C", "COBOL").
    pub tag: &'static str,
    /// Nombre legible.
    pub name: &'static str,
    pub pid: u32,
    pub tid: u32,
    /// Tamano del archivo .bex embebido.
    pub image_bytes: u32,
    /// Bytes de codigo+datos realmente mapeados en el espacio de usuario.
    pub code_bytes: u32,
    pub sections: u8,
    pub entry_va: u64,
    /// `false` = el BEX no paso la admision (formato, memoria, slots).
    pub admitted: bool,
}

const MAX_PROGRAMS: usize = 8;
const EMPTY_RECORD: ProgramRecord = ProgramRecord {
    tag: "", name: "", pid: 0, tid: 0,
    image_bytes: 0, code_bytes: 0, sections: 0, entry_va: 0, admitted: false,
};
static mut PROGRAMS: [ProgramRecord; MAX_PROGRAMS] = [EMPTY_RECORD; MAX_PROGRAMS];
static mut PROGRAM_COUNT: usize = 0;
/// Cuantas entradas se cayeron del registro por el principio. Se cuenta para
/// que la tabla de CABINA no diga "ocho programas" cuando van veinte.
static mut PROGRAMS_OLVIDADOS: usize = 0;
/// El siguiente pid. Monotono y SUYO.
///
/// Antes salia de `PROGRAM_COUNT`: un pid derivado de la longitud de una
/// bitacora. Cuando la bitacora se llenaba dejaba de crecer, asi que el
/// siguiente pid se repetia -- y el pid es lo que encauza la salida de un hijo a
/// la consola de quien lo lanzo. Dos procesos con el mismo pid se habrian
/// mezclado la salida.
static mut NEXT_PID: u32 = 1;

/// Abre una entrada del registro ANTES de intentar la admision, para que un
/// programa rechazado tambien aparezca -- un hueco silencioso no explica nada.
///
/// Cuando se llena, tira la MAS VIEJA y corre el resto. Antes se descartaba la
/// nueva, o sea que la bitacora se congelaba en los demos del arranque justo
/// cuando lo que hacia falta era ver el ultimo `run`. En una tabla de ocho el
/// corrimiento es gratis, y a cambio la foto de CABINA habla del presente.
fn record_open(tag: &'static str, name: &'static str, pid: u32, image_bytes: u32) {
    unsafe {
        if PROGRAM_COUNT >= MAX_PROGRAMS {
            let arr = core::ptr::addr_of_mut!(PROGRAMS) as *mut ProgramRecord;
            for i in 1..MAX_PROGRAMS {
                *arr.add(i - 1) = *arr.add(i);
            }
            PROGRAM_COUNT = MAX_PROGRAMS - 1;
            PROGRAMS_OLVIDADOS += 1;
        }
        PROGRAMS[PROGRAM_COUNT] = ProgramRecord {
            tag, name, pid, tid: 0, image_bytes,
            code_bytes: 0, sections: 0, entry_va: 0, admitted: false,
        };
        PROGRAM_COUNT += 1;
    }
}

/// Programas que ya no estan en el registro por falta de sitio.
pub fn programas_olvidados() -> usize {
    unsafe { PROGRAMS_OLVIDADOS }
}

/// La entrada abierta para `pid`, si existe.
unsafe fn record_mut(pid: u32) -> Option<&'static mut ProgramRecord> {
    let n = PROGRAM_COUNT;
    let arr = core::ptr::addr_of_mut!(PROGRAMS) as *mut ProgramRecord;
    for i in 0..n {
        let r = &mut *arr.add(i);
        if r.pid == pid { return Some(r); }
    }
    None
}

/// Todos los programas que el kernel ha intentado ejecutar.
pub fn programs() -> &'static [ProgramRecord] {
    unsafe {
        let arr = core::ptr::addr_of!(PROGRAMS) as *const ProgramRecord;
        core::slice::from_raw_parts(arr, PROGRAM_COUNT)
    }
}
