//! Ring 3 process creation from BEX images (F2).
//!
//! Pipeline: BootContext payload → `bex::inspect` (validated mapping plan)
//! → fresh user address space → frames copied/zeroed per section → user
//! stack → 16 BMO Channel estuaries mapped U/S → fabricated Ring 3 trap
//! frame → `scheduler::spawn_user`. The first timer tick after
//! `timer::enable()` preempts the shell and enters CPL3 via iretq.
//!
//! v1 deliberately keeps the section leaf frames alive for the whole life
//! of the system: the single init process does not exit-reclaim (that is
//! part of the EXIT hardening work, with per-task allocation lists).

use boot_context::BootContext;

use crate::ring0::task::bex;
use crate::ring0::obj::channel;
use crate::ring0::mm::{self, phys, vmm};
use crate::ring0::task::scheduler;
use crate::ring0::plat::trap;

const USER_STACK_PAGES: u64 = 16; // 64 KiB
/// 16 KiB de pila de kernel por tarea.
///
/// Eran 8 KiB cuando el contexto guardado ocupaba 720 bytes. Con XSAVE ocupa
/// ~3,3 KiB —el área de estado extendido es de 3072— y cada trap se lleva eso
/// de la pila antes de que el despachador de Rust haga nada. Con 8 KiB un
/// fault anidado sobre un tick de timer se salía. El coste de subirlo son dos
/// páginas por tarea; el coste de no subirlo es corromper la pila de al lado.
const KERNEL_STACK_PAGES: u64 = 4;

// Que quepa no es una esperanza: se comprueba al compilar. Si alguien sube
// XSAVE_AREA sin tocar esto, el build se para aquí y no en el hardware.
const _: () = assert!(
    trap::MIN_TASK_STACK <= (KERNEL_STACK_PAGES * mm::PAGE) as usize,
    "la pila de kernel por tarea no cubre un contexto con XSAVE"
);

static mut TSS_PTR: u64 = 0;

/// Last outcome of `spawn_init`, kept so `phase::main` can surface it on the
/// dashboard *after* the screen is cleared (spawn_init runs before that).
static mut INIT_STATUS: &str = "not attempted";

fn set_status(s: &'static str) {
    unsafe { INIT_STATUS = s };
}

/// Human-readable result of the last `spawn_init` call, for on-screen report.
pub fn init_status() -> &'static str {
    unsafe { INIT_STATUS }
}

/// Embedded "hola mundo" Ring 3 program (generated by `toolchain/tools/hello-bex`).
/// When the boot chain reserves no Ring 3 payload, this is admitted as the
/// init process so BMO always demonstrates the full CPL3 → INVOKE → CPL0
/// chain on its own — no keyboard, no storage, no external image required.
static INIT_HELLO_BEX: &[u8] = include_bytes!("../init_hello.bex");

/// Programa C compilado por `toolchain/lang/c` (fuente:
/// `toolchain/lang/c/examples/hola_C.c`).
static HOLA_C_BEX: &[u8] = include_bytes!("../hola_C.bex");

/// Programa COBOL compilado por `toolchain/lang/cobol` (fuente:
/// `toolchain/lang/cobol/examples/hola_COBOL.cob`).
static HOLA_COBOL_BEX: &[u8] = include_bytes!("../hola_COBOL.bex");
/// El par cliente/servidor de Endpoint RPC. Se regeneran con
/// `cargo run -p bmo-rpc-demo -- <srv> <cli>` y se commitean, igual que los
/// demas demos.
static RPC_SRV_BEX: &[u8] = include_bytes!("../rpc_srv.bex");
static RPC_CLI_BEX: &[u8] = include_bytes!("../rpc_cli.bex");

// ★ EL COMPOSITOR YA NO ESTÁ AQUÍ.
//
// Vivía en esta lista como `include_bytes!("../compositor.bex")`, y eso era la
// deuda que `fs.rs` lleva describiendo desde que existe: un binario de Ring 3
// dentro del binario de Ring 0. Cambiar un píxel del escritorio obligaba a
// recompilar el sistema operativo entero y reflashear — y además metía en el
// repositorio un blob de 24 KiB que `build.ps1` reescribía en CADA build.
//
// Ahora se carga del volumen de datos, como cualquier programa. El sitio donde
// se arranca es `core::phase`, y no por capricho: **el disco todavía no está
// montado cuando se llama a `spawn_init`**. `dev::disk::init` y `fs::mount_data`
// pasan mucho después, así que aquí no habría de dónde leerlo.
//
// Los cinco demos de abajo SÍ se quedan embebidos, y eso también es una
// decisión: son la red que demuestra la cadena CPL3 → INVOKE → CPL0 **sin
// depender de un disco**. El día que el SATA no enumere, BMO tiene que poder
// seguir enseñando que Ring 3 funciona.

/// Los programas Ring 3 que BMO admite al arrancar cuando la cadena de
/// arranque no reservo ninguno.
///
/// Son TRES procesos separados, con su propio espacio de direcciones y su
/// propia tabla de capabilities. El primero es el hola-mundo en ensamblador
/// que valido la cadena CPL3 en su dia; los otros dos salen de los
/// compiladores de C y COBOL de BMO — es la primera vez que un lenguaje de
/// alto nivel compilado aqui corre sobre el metal.
///
/// Si uno falla al admitirse, se registra y se sigue con los demas: el
/// aislamiento de fallos existe justo para que un programa malo no se lleve
/// por delante al sistema.
/// `(etiqueta corta para el log, nombre legible, imagen BEX)`
static DEMOS: &[(&str, &str, &[u8])] = &[
    ("asm", "init_hello (asm)", INIT_HELLO_BEX),
    ("C", "hola_C (C)", HOLA_C_BEX),
    ("COBOL", "hola_COBOL (COBOL)", HOLA_COBOL_BEX),
    // El par que prueba Endpoint RPC. El servidor va PRIMERO para que tenga
    // el primer turno y cree el endpoint; aun asi el cliente reintenta
    // cediendo el turno, porque el orden del planificador no es una garantia
    // sobre la que se pueda construir.
    ("srv", "rpc_servidor", RPC_SRV_BEX),
    ("cli", "rpc_cliente", RPC_CLI_BEX),
];

/// Capture the TSS location from the BootContext (identity-mapped).
pub fn init(ctx: &BootContext) {
    unsafe { TSS_PTR = ctx.tss_ptr };
}

/// Update TSS.RSP0: the kernel stack the CPU switches to when Ring 3 code
/// of the *current* task takes an interrupt. Called at every switch into a
/// user task.
pub fn set_tss_rsp0(top: u64) {
    let tss = unsafe { TSS_PTR };
    if tss == 0 {
        return;
    }
    unsafe {
        ((tss + 4) as *mut u32).write_volatile(top as u32);
        ((tss + 8) as *mut u32).write_volatile((top >> 32) as u32);
    }
}

fn log(msg: &str) {
    crate::ring0::dev::console::serial_write(msg);
}

/// Load the init process from the BootContext Ring 3 payload, if one was
/// reserved by the boot chain. Returns the new TID. With no payload this
/// is a no-op so boot stays exactly as before.
pub fn spawn_init(ctx: &BootContext) -> Option<u32> {
    // Un payload de la cadena de arranque manda sobre todo lo demás.
    if ctx.ring3_payload_phys != 0 && ctx.ring3_payload_size >= 48 {
        let bytes = unsafe {
            core::slice::from_raw_parts(
                mm::phys_to_virt(ctx.ring3_payload_phys) as *const u8,
                ctx.ring3_payload_size as usize,
            )
        };
        return admit_payload(bytes, 1);
    }

    // ★ SIN PAYLOAD EXTERNO NO SE ARRANCA NADA.
    //
    // Aquí se admitían cinco programas de ejemplo en cada arranque: el hola
    // mundo en ensamblador, el de C, el de COBOL y el par de RPC. Su trabajo
    // era demostrar que Ring 3 existía, que un `.bex` de cada lenguaje corría
    // y que dos procesos podían hablarse. **Los tres están demostrados y
    // fotografiados**, así que a partir de aquí no demuestran: estorban.
    //
    // Y estorbaban de verdad, no en abstracto. `init_hello` **reclama la
    // pantalla** para enseñar que Ring 3 puede pintarla; arrancaba a la vez
    // que el escritorio, ganaba, pintaba tres líneas, terminaba — y al morir
    // el kernel recuperaba la pantalla y repintaba su panel encima del
    // escritorio recién nacido. Eso es lo que salía en cada foto y lo que
    // llevó a acusar tres veces al compositor de morirse.
    //
    // Un arranque no es una demostración: es arrancar. Lo que se enseña es la
    // presentación de Ring 3 y el escritorio, y punto.
    //
    // Y no se pierde nada, porque **los ejemplos viven en el disco**: se
    // lanzan a mano con `run c/holac.bex`, `run cobol/banco.bex`,
    // `run ada/cierre.bex`. Ésos son además los de verdad — los compilados por
    // el toolchain en cada build, no las copias congeladas dentro del kernel.
    //
    // ★ Al dejar de arrancarlos, los `.bex` embebidos pasaron a ser código
    // muerto y el enlazador se los llevó: **el kernel adelgazó 37 KB**. Ése es
    // el precio real que se estaba pagando por una demostración ya hecha.
    log("[proc] sin payload de arranque: no se admite nada (los ejemplos van a mano)\n");
    crate::ring0::cabina::info("ring3", "sin payload: el escritorio es el unico Ring 3", 0);
    None
}

/// Los ejemplos embebidos, para lanzarlos **a mano**. Ver [`spawn_init`]: ya no
/// se arrancan solos.
#[allow(dead_code)]
fn admitir_ejemplos() -> Option<u32> {
    let mut first: Option<u32> = None;
    let mut index = 0;
    while index < DEMOS.len() {
        let (tag, name, bytes) = DEMOS[index];
        let pid = index as u32 + 1;
        // El log tiene que decir de quién es cada línea ANTES de que el
        // proceso escriba la primera.
        crate::ring0::uconsole::set_tag(pid, tag);
        // La entrada del registro se abre ANTES de intentar admitirlo: si el
        // BEX es rechazado, tiene que aparecer igual en la tabla, marcado.
        record_open(tag, name, pid, bytes.len() as u32);
        match admit_payload(bytes, pid) {
            Some(tid) => {
                crate::ring0::cabina::info(name, "programa Ring 3 admitido", tid as u64);
                if first.is_none() {
                    first = Some(tid);
                }
            }
            None => {
                // Que uno no entre no puede tumbar a los demás: el
                // aislamiento de fallos existe exactamente para esto.
                crate::ring0::cabina::warn(name, "no se pudo admitir", pid as u64);
            }
        }
        index += 1;
    }
    first
}

// ── Programas que vienen del DISCO ──────────────────────────────────────────

/// Nombres de los programas cargados de disco.
///
/// `ProgramRecord` guarda `&'static str` porque los tres demos son literales
/// del binario. Un programa que llega del disco trae su nombre en un buffer
/// prestado que desaparece al volver del comando, así que se copia aquí: un
/// almacén estático pequeño cuya vida SÍ es la del kernel. Sin `alloc`, esta
/// es la forma honesta de tener un `&'static str` que no existía al compilar.
const MAX_DISK_NAMES: usize = 6;
const DISK_NAME_LEN: usize = 24;
static mut DISK_NAMES: [[u8; DISK_NAME_LEN]; MAX_DISK_NAMES] = [[0; DISK_NAME_LEN]; MAX_DISK_NAMES];
static mut DISK_NAME_COUNT: usize = 0;

fn intern_name(s: &str) -> &'static str {
    unsafe {
        // Si ya está guardado, se reusa. Lanzar `apps/batch.bex` cinco veces
        // gastaba cinco ranuras de seis, y a la séptima todos los programas se
        // llamaban "disco" en la bitácora — que es justamente cuando hace falta
        // saber cuál era.
        let arr_ro = core::ptr::addr_of!(DISK_NAMES) as *const [u8; DISK_NAME_LEN];
        for i in 0..DISK_NAME_COUNT {
            let buf = &*arr_ro.add(i);
            let n = s.len().min(DISK_NAME_LEN);
            if buf[..n] == s.as_bytes()[..n] && (n == DISK_NAME_LEN || buf[n] == 0) {
                let p = buf.as_ptr();
                if let Ok(t) = core::str::from_utf8(core::slice::from_raw_parts(p, n)) {
                    return t;
                }
            }
        }
        if DISK_NAME_COUNT >= MAX_DISK_NAMES { return "disco"; }
        let slot = DISK_NAME_COUNT;
        DISK_NAME_COUNT += 1;
        let arr = core::ptr::addr_of_mut!(DISK_NAMES) as *mut [u8; DISK_NAME_LEN];
        let buf = &mut *arr.add(slot);
        let n = s.len().min(DISK_NAME_LEN);
        buf[..n].copy_from_slice(&s.as_bytes()[..n]);
        let p = buf.as_ptr();
        core::str::from_utf8(core::slice::from_raw_parts(p, n)).unwrap_or("disco")
    }
}

/// El siguiente pid libre.
///
/// Antes el pid era el ÍNDICE del demo en su tabla, así que solo podían
/// existir los tres de siempre y no había forma de añadir un cuarto. Ahora sale
/// del registro, que es quien sabe cuántos programas se han intentado admitir.
fn next_pid() -> u32 {
    unsafe {
        let p = NEXT_PID;
        NEXT_PID = NEXT_PID.wrapping_add(1).max(1);
        p
    }
}

/// ¿Queda sitio para otro programa? **Se lo pregunta al planificador.**
///
/// ★ Aquí vivía el bug que dejaba la máquina sin poder lanzar nada. Esto era
/// `PROGRAM_COUNT < MAX_PROGRAMS`, o sea la longitud del REGISTRO HISTÓRICO de
/// abajo — una bitácora de ocho entradas que a propósito no baja nunca, porque
/// apunta también los programas que se rechazaron. El arranque gasta seis
/// (cinco demos más el compositor), así que al tercer `run` la máquina decía
/// "sin hueco" y no volvía a admitir un programa hasta reiniciar. Y no era
/// mentira a medias: había 58 ranuras de tarea libres.
///
/// La capacidad viva la tiene el planificador, que recicla la ranura cuando
/// `reap` recoge una tarea terminada. Un registro cuenta lo que PASÓ; sólo el
/// planificador sabe lo que HAY.
pub fn has_room() -> bool {
    crate::ring0::task::scheduler::hay_hueco()
}

/// Admite un programa BEX que viene de un archivo, no del propio binario.
///
/// Es la razón de ser de todo el trabajo de disco: hasta aquí los programas
/// Ring 3 viajaban dentro del kernel con `include_bytes!` y cambiar una línea
/// de un `hola mundo` obligaba a recompilar el sistema operativo y reflashear.
///
/// Devuelve `(tid, pid)`. El pid hace falta para encauzar la salida del
/// hijo a la consola de quien lo lanzo (ver `ring0/consola.rs`).
pub fn admit_from_disk(name: &str, bytes: &[u8]) -> Option<(u32, u32)> {
    if !has_room() { return None; }
    let pid = next_pid();
    let stored = intern_name(name);
    // La etiqueta del log ANTES de que el proceso escriba su primera línea,
    // igual que con los demos: si no, la primera línea sale sin dueño.
    crate::ring0::uconsole::set_tag(pid, stored);
    record_open(stored, stored, pid, bytes.len() as u32);
    match admit_payload(bytes, pid) {
        Some(tid) => {
            crate::ring0::cabina::info("proc", "programa admitido DESDE DISCO", tid as u64);
            Some((tid, pid))
        }
        None => {
            crate::ring0::cabina::warn("proc", "el .bex de disco no paso la admision", pid as u64);
            None
        }
    }
}

/// Admite UN programa BEX como proceso Ring 3 con el `pid` indicado.
fn admit_payload(bytes: &[u8], pid: u32) -> Option<u32> {
    set_status("admitting (alloc/map)");
    let plan = match bex::inspect(bytes) {
        Ok(p) => p,
        Err(_) => {
            log("[proc] FATAL: payload failed BEX admission\n");
            set_status("BEX admission failed");
            return None;
        }
    };
    let aspace = vmm::new_address_space()?;

    // Sections: assigned sequentially from USER_IMAGE_BASE, honoring each
    // section's alignment. entry_offset is relative to the Code section.
    let mut va_cursor = vmm::USER_IMAGE_BASE;
    let mut entry_va: u64 = 0;
    let mut code_bytes: u32 = 0;
    for i in 0..plan.section_count {
        let s = plan.sections[i];
        let align = s.alignment as u64;
        va_cursor = (va_cursor + align - 1) & !(align - 1);
        let va_start = va_cursor;
        let pages = (s.mem_size + mm::PAGE - 1) / mm::PAGE;
        let writable = s.flags & bex::SECTION_FLAG_EXEC == 0;
        for p in 0..pages {
            let frame = phys::alloc_frame()?;
            phys::zero_frame(frame);
            let chunk = p * mm::PAGE;
            if chunk < s.file_size {
                let n = (s.file_size - chunk).min(mm::PAGE) as usize;
                unsafe {
                    core::ptr::copy_nonoverlapping(
                        bytes.as_ptr().add((s.file_offset + chunk) as usize),
                        mm::phys_to_virt(frame) as *mut u8,
                        n,
                    );
                }
            }
            if vmm::map_page(aspace, va_start + p * mm::PAGE, frame, true, writable).is_err() {
                log("[proc] FATAL: section map failed\n");
                return None;
            }
        }
        if s.kind == bex::SECTION_CODE {
            entry_va = va_start + plan.entry_offset;
        }
        code_bytes = code_bytes.saturating_add(s.mem_size as u32);
        va_cursor = va_start + pages * mm::PAGE;
    }
    if entry_va == 0 {
        log("[proc] FATAL: no entry point\n");
        return None;
    }

    // User stack (64 KiB) just below USER_STACK_TOP.
    for p in 0..USER_STACK_PAGES {
        let frame = phys::alloc_frame()?;
        phys::zero_frame(frame);
        let va = vmm::USER_STACK_TOP - (p + 1) * mm::PAGE;
        if vmm::map_page(aspace, va, frame, true, true).is_err() {
            log("[proc] FATAL: stack map failed\n");
            return None;
        }
    }

    // The 16 BMO Channel estuaries, shared U/S with Ring 0.
    for i in 0..boot_context::MAX_CHANNEL_PAGES {
        let va = vmm::CHANNEL_VA_BASE + (i as u64) * mm::PAGE;
        if vmm::map_page(aspace, va, channel::page_phys(i), true, true).is_err() {
            log("[proc] FATAL: channel map failed\n");
            return None;
        }
    }

    // Kernel landing stack + fabricated Ring 3 context. The frames MUST be
    // physically contiguous: the stack is addressed linearly through the
    // physmap, and `fabricate` writes the context in the TOP page — with two
    // independent alloc_frame calls that page is `base+4K` physical, a frame
    // nobody granted us unless the allocator happened to return neighbors
    // (true on QEMU's clean map, false on real memory maps with holes; the
    // context then lives in a foreign/free frame and dies with the next
    // zero_frame — restored as zeros: backptr=0, pops to rsp=0x78, iretq
    // with cs=0 ⇒ the observed #GP(0)).
    let kstack_base = phys::alloc_frames_contig(KERNEL_STACK_PAGES)?;
    let kstack_top = mm::phys_to_virt(kstack_base) + KERNEL_STACK_PAGES * mm::PAGE;
    let context = unsafe { trap::fabricate(kstack_top, entry_va, 0, true, vmm::USER_STACK_TOP) };

    let tid = scheduler::spawn_user(pid, context, kstack_base, KERNEL_STACK_PAGES, kstack_top, aspace, 0)?;
    // F3: seed the init process's capability table — one estuary handle
    // per BMO Channel page, discoverable via TASK_OP_CHANNEL_OPEN.
    crate::ring0::obj::cap::seed_init(pid);
    log("[proc] init.bex admitted: Ring 3 entry at 0x");
    crate::ring0::dev::console::serial_write_u64(entry_va, 16);
    log("\n");
    set_status("admitted");
    // Anotar lo que el BEX declaraba: el registro de programas se llena aquí,
    // con los datos del plan de carga que acabamos de honrar.
    unsafe {
        if let Some(r) = record_mut(pid) {
            r.tid = tid;
            r.sections = plan.section_count as u8;
            r.entry_va = entry_va;
            r.code_bytes = code_bytes;
            r.admitted = true;
        }
    }
    Some(tid)
}

// ── Registro de programas ───────────────────────────────────────────────────
//
// Qué se admitió, de qué tamaño, dónde entra y con qué pid. El log cuenta la
// historia según pasa; esto es la FOTO: una tabla que se puede mirar después,
// cuando las líneas del log ya rodaron y desaparecieron.

/// Un programa BEX que el kernel intentó admitir.
#[derive(Clone, Copy)]
pub struct ProgramRecord {
    /// Etiqueta corta con la que sale en el log ("asm", "C", "COBOL").
    pub tag: &'static str,
    /// Nombre legible.
    pub name: &'static str,
    pub pid: u32,
    pub tid: u32,
    /// Tamaño del archivo .bex embebido.
    pub image_bytes: u32,
    /// Bytes de código+datos realmente mapeados en el espacio de usuario.
    pub code_bytes: u32,
    pub sections: u8,
    pub entry_va: u64,
    /// `false` = el BEX no pasó la admisión (formato, memoria, slots).
    pub admitted: bool,
}

const MAX_PROGRAMS: usize = 8;
const EMPTY_RECORD: ProgramRecord = ProgramRecord {
    tag: "", name: "", pid: 0, tid: 0,
    image_bytes: 0, code_bytes: 0, sections: 0, entry_va: 0, admitted: false,
};
static mut PROGRAMS: [ProgramRecord; MAX_PROGRAMS] = [EMPTY_RECORD; MAX_PROGRAMS];
static mut PROGRAM_COUNT: usize = 0;
/// Cuántas entradas se cayeron del registro por el principio. Se cuenta para
/// que la tabla de CABINA no diga "ocho programas" cuando van veinte.
static mut PROGRAMS_OLVIDADOS: usize = 0;
/// El siguiente pid. Monótono y SUYO.
///
/// Antes salía de `PROGRAM_COUNT`: un pid derivado de la longitud de una
/// bitácora. Cuando la bitácora se llenaba dejaba de crecer, así que el
/// siguiente pid se repetía — y el pid es lo que encauza la salida de un hijo a
/// la consola de quien lo lanzó. Dos procesos con el mismo pid se habrían
/// mezclado la salida.
static mut NEXT_PID: u32 = 1;

/// Abre una entrada del registro ANTES de intentar la admisión, para que un
/// programa rechazado también aparezca — un hueco silencioso no explica nada.
///
/// Cuando se llena, tira la MÁS VIEJA y corre el resto. Antes se descartaba la
/// nueva, o sea que la bitácora se congelaba en los demos del arranque justo
/// cuando lo que hacía falta era ver el último `run`. En una tabla de ocho el
/// corrimiento es gratis, y a cambio la foto de CABINA habla del presente.
fn record_open(tag: &'static str, name: &'static str, pid: u32, image_bytes: u32) {
    unsafe {
        if PROGRAM_COUNT >= MAX_PROGRAMS {
            let arr = core::ptr::addr_of_mut!(PROGRAMS) as *mut ProgramRecord;
            for i in 1..MAX_PROGRAMS {
                *arr.add(i - 1) = *arr.add(i);
            }
            PROGRAM_COUNT = MAX_PROGRAMS - 1;
            PROGRAMS_OLVIDADOS += 1;
        }
        PROGRAMS[PROGRAM_COUNT] = ProgramRecord {
            tag, name, pid, tid: 0, image_bytes,
            code_bytes: 0, sections: 0, entry_va: 0, admitted: false,
        };
        PROGRAM_COUNT += 1;
    }
}

/// Programas que ya no están en el registro por falta de sitio.
pub fn programas_olvidados() -> usize {
    unsafe { PROGRAMS_OLVIDADOS }
}

/// La entrada abierta para `pid`, si existe.
unsafe fn record_mut(pid: u32) -> Option<&'static mut ProgramRecord> {
    let n = PROGRAM_COUNT;
    let arr = core::ptr::addr_of_mut!(PROGRAMS) as *mut ProgramRecord;
    for i in 0..n {
        let r = &mut *arr.add(i);
        if r.pid == pid { return Some(r); }
    }
    None
}

/// Todos los programas que el kernel ha intentado ejecutar.
pub fn programs() -> &'static [ProgramRecord] {
    unsafe {
        let arr = core::ptr::addr_of!(PROGRAMS) as *const ProgramRecord;
        core::slice::from_raw_parts(arr, PROGRAM_COUNT)
    }
}
