//! BMO Symbol Linker — reads Ring 3 .elf module files, extracts exported
//! symbols, and generates BMO_SYMBOLS.toml for runtime resolution.
//!
//! Usage: bmo-linker <output.toml> <module1.elf> <module2.elf> ...
//!
//! Each .elf module contributes its no_mangle/global function symbols.
//! The output TOML file maps category → symbol → virtual address.
use std::env;
use std::fs;
use std::io::Write;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("Usage: {} <output.toml> <module1.elf> ...", args[0]);
        std::process::exit(1);
    }

    let output_path = &args[1];
    let mut output = String::from("# BMO Symbol Registry — auto-generated by bmo-linker\n");
    output.push_str("# Maps module:category → symbol → virtual address\n\n");

    for elf_path in &args[2..] {
        let data = match fs::read(elf_path) {
            Ok(d) => d,
            Err(e) => {
                eprintln!("SKIP {}: {}", elf_path, e);
                continue;
            }
        };

        let elf = match goblin::elf::Elf::parse(&data) {
            Ok(e) => e,
            Err(e) => {
                eprintln!("SKIP {} parse: {}", elf_path, e);
                continue;
            }
        };

        // Derive category from filename: "mod_timeback.elf" → "timeback"
        let stem = std::path::Path::new(elf_path)
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy();
        let category = stem
            .strip_prefix("mod_")
            .unwrap_or(&stem)
            .replace('-', "_");

        let mut count = 0u32;
        let strtab = &elf.strtab;

        for sym in &elf.syms {
            let name = strtab.get_at(sym.st_name).unwrap_or("");
            if name.is_empty() { continue; }

            // Only global/func symbols with known address
            let st_type = goblin::elf::sym::st_type(sym.st_info);
            let st_bind = goblin::elf::sym::st_bind(sym.st_info);
            if st_bind != goblin::elf::sym::STB_GLOBAL { continue; }
            if st_type != goblin::elf::sym::STT_FUNC { continue; }
            if sym.st_value == 0 { continue; }

            // Filter: only useful public APIs (skip internal/compiler symbols)
            if name.starts_with("_") && !name.starts_with("_module_start") { continue; }
            if name.contains('.') { continue; }
            if name.starts_with("__") { continue; }

            output.push_str(&format!(
                "[{}.{}]\naddr = {}\n\n",
                category, name, sym.st_value
            ));
            count += 1;
        }

        eprintln!("  {}: {} symbols → {}", elf_path, count, category);
    }

    fs::write(output_path, &output).expect("failed to write output");
    eprintln!("Generated: {}", output_path);
}
