[package]
name = "bmo-core"
version = "1.8.16"
edition = "2021"
authors = ["BMO Project"]
description = "BMO Core - logical Ring 3 kernel (windowing, UI, FS, desktop, BEF loader)"

[dependencies]
bmo-abi = { path = "../../../Uso_Reales_Crates/abi/bmo-abi" }
bmo-hal = { path = "../../../Uso_Reales_Crates/shared/bmo-hal" }
timeback = { path = "../../../Uso_Reales_Crates/services/timeback" }
bmo-boot-protocol = { path = "../../../kernel/Boot_Protocol" }
goblin = { path = "../../plugins/goblin", default-features = false, features = ["alloc", "elf32", "elf64", "endian_fd", "pe32", "pe64"] }
