[package]
name = "bmo-core"
version = "1.8.16"
edition = "2021"
authors = ["BMO Project"]
description = "BMO Core - logical Ring 3 kernel (windowing, UI, FS, desktop, BEF loader)"

[dependencies]
bmo-abi = { path = "../bmo_abi" }
bmo-input = { path = "../bmo_input" }
bmo-boot-protocol = { path = "../boot_protocol" }
goblin = { path = "../goblin", default-features = false, features = ["alloc", "elf32", "elf64", "endian_fd"] }
